#import "../../template.typ": r, exercise

#exercise(57, "论赌铜钱", "LUNG TOO-DOONG-DIEN")

#r("Too-doong-dien-kuh", "赌铜钱个") #r("(5) 'e-tshu", "害处")#footnote[Injury.] #r("z", "是") #r("(6) wo", "话")#footnote[Cannot be all told.] #r("'veh-dzing-kuh.", "勿尽个。") 
#r("Zauh-nyih", "昨日") #r("ngoo", "我") #r("thing-tuh", "听得") #r("liang-we", "两位") #r("(7) mak-sang", "陌生")#footnote["A stranger friend".] #r("bang-yeu,", "朋友，") #r("la", "拉") #r("ngoo-nyi", "我伲") #r("sia-z-kan", "写字间") #r("li", "里") #r("kaung", "讲") #r("ih-tsaung", "一桩") #r("koo-tien,", "古典，") #r("z", "是") #r("kaung-tau", "讲到") #r("ih-kuh", "一个") #r("too-doong-dien-kuh", "赌铜钱个") #r("nyung,", "人") #r("su-theh", "输脱") #r("nyi", "二百块") #r("pak-kwhe", "洋钱。") #r("yang-dien.", "现在") 
#r("Yien-dze", "我") #r("ngoo", "也") #r("'a", "要") #r("iau", "担") #r("tan", "一桩") #r("ih-tsaung", "古典") #r("koo-tien", "翻之") #r("(8) fan-ts", "上海")#footnote[Translate.] #r("Zaung-he", "土白") #r("thoo-bak", "咾") #r("lau", "读") #r("dok", "拨哪") #r("peh", "听。") #r("na", "拉") #r("thing.", "松江") 

#r("La", "地方") #r("(1) Soong-kaung", "有")#footnote[Sungkiang.] #r("di-faung", "一位，") #r("yeu", "姓") #r("ih-we,", "陆") #r("sing", "名头") #r("Lok,", "叫") #r("ming-deu", "义泉。") #r("kyau", "伊") #r("Nyi-zien,", "是") #r("yi", "非常") #r("z", "个") #r("(2) fi-dzang", "欢喜")#footnote[Unusual.] #r("kuh", "叉麻雀。") #r("hwen-hyi", "有") #r("tsho", "一日") #r("mo-tsiang.", "伊个") 
#r("Yeu", "屋里") #r("ih-nyih", "有") #r("la", "喜事") #r("yi-kuh", "咾") #r("ok-li,", "伊") #r("yeu", "约之") #r("hyi-z", "几个") #r("lau", "同行中个") #r("yi", "朋友，") #r("(3) iak-ts", "到")#footnote[Made an appointment.] #r("kyi-kuh", "伊个") #r("(4) doong-'aung-tsoong-kuh", "屋里")#footnote[Friends of the same occupation.] #r("bang-yeu,", "去") #r("tau", "叉麻雀。") #r("yi-kuh", "伊拉") #r("ok-li", "一夜") #r("chi", "叉") #r("tsho", "到") #r("mo-tsiang.", "天亮") 
#r("Yi-la", "咾") #r("ih-ya,", "勿曾") #r("tsho", "睏；") #r("tau", "到之") #r("thien-liang", "第二日") #r("lau", "望望") #r("'veh-zung", "天亮。") #r("kwhung;", "第位") #r("tau-ts", "朋友") #r("di-nyi", "带之") #r("nyih", "二百块") #r("(5) maung-maung", "洋钱")#footnote[Looking for daybreak.] #r("thien", "要") #r("liang.", "到") 
#r("Di-we", "上海") #r("bang-yeu", "来") #r("ta-ts", "攞货式。") #r("nyi", "伊") #r("pak", "是") #r("kwhe-yang-dien,", "趁之") #r("iau", "火车") #r("tau", "咾") #r("Zaung-he", "来个。") #r("le", "坐") #r("(6) tshoen", "拉")#footnote[Collect, gather together.] #r("hoo-suh.", "车上") #r("Yi", "觉着") #r("z", "疲倦") #r("tshung-ts", "咾") #r("hoo-tsho", "打磕睡。") #r("lau", "难末") #r("le-kuh,", "伊") #r("zoo", "划之") #r("la", "一根") #r("tsho", "洋火") #r("laung", "咾") #r("kauh-dzak", "吃") #r("bi-joen", "香烟") #r("lau,", "要") #r("(7) tang-kheh-tshoong.", "戒脱")#footnote[Sleepy, nodding.] 
#r("Nan-meh", "伊个") #r("yi", "打磕睡，") #r("(8) wak-ts", "但是")#footnote[Struck a match.] #r("ih-kung", "勿") #r("yang-hoo", "能够。") #r("lau", "伊") #r("chuh", "呼之") #r("(9) hyang-ien,", "两口")#footnote[Cigarette.] #r("iau", "烟") #r("ka-theh", "伊个") #r("yi-kuh", "眼睛") #r("tang-kheh-tshoong,", "闭拢之") #r("dan-z", "咾") #r("'veh", "睏着者。") #r("nung-keu.", "勿多") 
#r("Yi", "几分") #r("(10) hoo-ts", "钟")#footnote[Took a few puffs.] #r("liang", "就") #r("kheu", "打昏胞。") #r("ien,", "拉") #r("yi-kuh", "伊个") #r("ngan-tsing", "旁边") #r("(11) pi-loong-ts", "有")#footnote[Closed.] #r("lau", "一个") #r("kwhung-dzak-tse.", "下流坯") 
#r("'Veh-too", "就") #r("kyi-fung", "轻轻能") #r("tsoong", "上来") #r("zieu", "偷脱") #r("(12) tang-hwung-doo.", "伊")#footnote[To snore.] 
#r("La", "手里个") #r("yi-kuh", "洋钱。") #r("baung-pien", "第个人") #r("yeu", "勿曾") #r("ih-kuh", "醒") #r("(13) 'au-lieu-phe,", "直")#footnote[Rascal.] #r("zieu", "等到") #r("chung-chung", "火车") #r("nung", "到之") #r("zaung", "上海") #r("le", "个") #r("theu", "车站") #r("theh", "上") #r("yi", "咾") #r("seu", "拢总") #r("li-kuh", "个") #r("yang-dien.", "搭客") 
#r("Di-kuh", "已经") #r("nyung", "去者。") #r("'veh-zung", "难末") #r("(14) sing,", "伊")#footnote[Awoke.] #r("dzuh-tung-tau", "醒转来") #r("hoo-tsho", "咾") #r("tau-ts", "晓得") #r("Zaung-he", "伊个") #r("kuh", "洋钱") #r("tsho-dzan", "是") #r("laung", "勿") #r("lau", "见者。") #r("loong-tsoong", "伊") #r("kuh", "四面") #r("(15) tah-khak", "去")#footnote[Passengers.] #r("i-kyung", "问问") #r("chi-tse,", "但是") #r("nan-meh", "问勿着") #r("yi", "是") #r("sing-tse-le", "啥人") #r("lau,", "偷个。") #r("hyau-tuh", "为之") #r("yi-kuh", "实在") #r("yang-dien", "个") #r("z", "事体") #r("'veh", "我") #r("kyien-tse.", "要") 
#r("Yi", "劝") #r("s", "诸位") #r("mien", "勿要") #r("chi", "赌铜钱") #r("mung-mung,", "也") #r("dan-z", "勿要") #r("mung-'veh-dzak", "搭") #r("z", "下流坯") #r("sa-nyung", "轧淘") #r("theu-kuh.", "咾") 
#r("We-ts", "做") #r("zeh-ke", "朋友。") #r("kuh", "comb") #r("z-thi,", "the") #r("ngoo", "hair") #r("iau", "Wash") #r("(1) choen", "comb")#footnote[Exhort.] #r("na", "the") #r("tsu-we", "hair") #r("'veh", "Wash") #r("iau", "comb") #r("too", "the") #r("doong-dien,", "hair") #r("'a", "Wash") #r("'veh-iau", "comb") #r("tah", "the") #r("'au-lieu-phe", "hair") #r("(2) gah-tau", "Wash")#footnote[Associate with.] #r("lau", "comb") #r("tsoo", "the") #r("bang-yeu.", "hair") 
