#import "../../template.typ": exercise, r

#exercise(63, "论骗铜钱个法则", "LUNG PHIEN DOONG-DIEN KUH FAH-TSUH")

#r("LUNG", "论") #r("PHIEN", "骗") #r("DOONG-DIEN", "铜钱") #r("KUH", "个") #r("FAH-TSUH.", "法则。")#footnote[Cheat, deceive.] #r("'Oo-zaung", "和尚")#footnote[Buddhist priest.] #r("z", "是") #r("ting", "顶") #r("lan-doo", "懒惰") #r("kuh", "个") #r("pak-sing,", "百姓。") #r("iung-we", "因为") #r("yi-la", "伊拉") #r("ih", "一") #r("nyien", "年") #r("tau", "到") #r("deu", "头") #r("'veh", "勿") #r("khung", "肯") #r("tsoo", "做") #r("sang-weh,", "生活。") #r("tsuh", "只") #r("hyau-tuh", "晓得") #r("chuh,", "吃") #r("tsak", "着") #r("lau", "咾") #r("beh-siang.", "勃相。") 

#r("Zak-zen", "若然") #r("yi-la", "伊拉") #r("m-meh", "无没") #r("doong-dien", "铜钱") #r("yoong", "用") #r("meh,", "末") #r("zieu", "就") #r("iau", "要") #r("siang", "想") #r("fah-tsuh", "法则") #r("le", "来") #r("phien", "骗") #r("bih-nyung", "别人") #r("kuh", "个") #r("doong-dien", "铜钱") #r("tse.", "哉。") 
#r("Zien-kuh", "前个") #r("nyoeh", "月") #r("ti,", "底") #r("la", "拉") #r("Soo-tseu", "苏州") #r("dzung", "城") #r("li", "里") #r("yeu", "有") #r("ih-zoo", "一座") #r("miau-li", "庙里") #r("kuh", "个") #r("'oo-zaung,", "和尚。") #r("yui-be-ts", "预备之") #r("ih-kan", "一间") #r("vaung-kan", "房间") #r("lau,", "咾") #r("la", "拉") #r("ziang-deu", "墙头") #r("laung", "上")#footnote[On the wall.] #r("khe-ts", "开之") #r("ih-kuh", "一个") #r("yoen-doong,", "圆洞。") #r("tan", "担") #r("ih-kuh", "一个") #r("lau", "老") #r("'oo-zaung", "和尚") #r("le", "来") #r("soo", "锁") #r("la", "拉") #r("vaung-kan", "房间") #r("li;", "里；") #r("kyau", "叫") #r("yi", "伊") #r("lih", "立") #r("la", "拉") #r("i-kuh", "伊个") #r("doong", "洞") #r("kheu-deu,", "口头") #r("peh", "拨") #r("bih-nyung", "别人") #r("chi", "去") #r("khoen,", "看。") 

#r("Tse", "再") #r("yeu", "有") #r("kyi", "几") #r("kuh", "个") #r("'oo-zaung", "和尚") #r("tau", "到") #r("siang-sing", "相信") #r("Veh-kyau", "佛教")#footnote[Buddhist religion.] #r("kuh", "个") #r("nyung-ka", "人家") #r("chi,", "去") #r("kau-soo", "告诉") #r("yi-la", "伊拉") #r("wo,", "话") #r("nyi", "伲") #r("kuh", "个") #r("lau", "老") #r("'oo-zaung", "和尚") #r("la", "拉") #r("maung-deu", "梦头")#footnote[Dream.] #r("li", "里") #r("khoen-kyien", "看见") #r("Kwen-iung-boo-sah", "观音菩萨")#footnote[Goddess of mercy.] #r("fung-foo", "吩咐") #r("yi", "伊") #r("iau", "要") #r("sieu-hau", "修好") #r("miau-li", "庙里") #r("kuh", "个") #r("vaung-ts.", "房子。") 

#r("Zak-zen", "若然") #r("yi", "伊") #r("nung-keu", "能够") #r("sieu-hau", "修好") #r("meh,", "末") #r("i-deu", "伊头") #r("kuh", "个") #r("pak-sing", "百姓") #r("khau-i", "可以") #r("zieu", "就") #r("tuh-dzak", "得着") #r("fok-chi.", "福气。") #r("Zak-zen", "若然") #r("yi", "伊") #r("'veh", "勿") #r("thing", "听") #r("yi", "伊") #r("kuh", "个") #r("seh-wo", "说话") #r("meh,", "末") #r("di-zoo", "第座") #r("miau-li", "庙里") #r("kuh", "个") #r("'oo-zaung", "和尚") #r("zen", "全") #r("iau", "要") #r("zeu", "受") #r("khoo-kuh.", "苦个。") 

#r("Nyi", "伲") #r("lau", "老") #r("'oo-zaung", "和尚") #r("dzoong", "从") #r("maung-deu", "梦头") #r("li", "里") #r("sing-tsen-le,", "醒转来") #r("hyau-tuh", "晓得") #r("boo-sah-kuh", "菩萨个") #r("seh-wo", "说话") #r("'veh", "勿") #r("z", "是") #r("ka-kuh,", "假个") #r("soo-i", "所以") #r("zieu", "就") #r("la", "拉") #r("boo-sah", "菩萨") #r("mien-zien", "面前") #r("kheh-deu", "磕头") #r("lau", "咾") #r("thau", "讨") #r("nyau.", "饶。")#footnote[Beg pardon.] #r("Yi", "伊") #r("dzing-nyoen", "情愿") #r("'veh", "勿") #r("chuh", "吃") #r("van", "饭") #r("lau", "咾") #r("lih", "立") #r("la", "拉") #r("i", "伊") #r("kan", "间") #r("vaung-ts", "房间") #r("li", "里") #r("tung", "等") #r("si.", "死。")#footnote[Until death.] 

#r("Nan-meh", "难末") #r("yeu", "有") #r("kyan-kwan", "交关") #r("siang-sing", "相信") #r("Veh-kyau-kuh", "佛教个") #r("nyung,", "人") #r("tau", "到") #r("miau", "庙") #r("li", "里") #r("le", "来") #r("kyoen", "捐") #r("doong-dien,", "铜钱") #r("paung-dzoo", "帮助") #r("yi-la", "伊拉") #r("sieu-tsauh", "修作") #r("vaung-ts", "房子") #r("lau,", "咾") #r("faung", "放") #r("di-kuh", "第个") #r("lau", "老") #r("'oo-zaung", "和尚") #r("tsheh-le", "出来") #r("tse.", "哉。")
