#import "../../template.typ": exercise, r

#exercise(42, "论小姐读书咾学生活", "LUNG SIAU-TSIA DOK-SU LAU 'AUH SANG-WEH")

#r("Ih-ka-nyung-ka", "一家人家") #r("yeu", "有") #r("san", "三") #r("we", "位") #r("siau-tsia", "小姐") #r("lau,", "咾，") #r("s-kuh", "四个") #r("nyi-ts;", "儿子；") 
#r("doo-kuh", "大个") #r("siau-tsia", "小姐") #r("zeh-lok", "十六") #r("soe,", "岁，") #r("siau-kuh", "小个") #r("siau-tsia", "小姐") #r("lok", "六") #r("soe;", "岁。") 
#r("doo-kuh", "大个") #r("nyi-ts", "儿子") #r("so-ng", "十五") #r("soe,", "岁，") #r("ting", "顶") #r("siau-kuh", "小个") #r("nyi-ts", "儿子") #r("liang", "两") #r("soe.", "岁。") 
#r("Siau-tsia", "小姐") #r("zen", "全") #r("la", "拉") #r("'auh-daung", "学堂") #r("li", "里") #r("dok-su", "读书") #r("lau", "咾") #r("'auh-zih", "学习")#footnote[Learn.] #r("ok-li-kuh", "屋里个") #r("sang-weh.", "生活。") 
#r("Yi-la", "伊拉") #r("zen", "全") #r("tshoong-ming", "聪明") #r("lau", "咾") #r("hwen-hyi", "欢喜") #r("dok-su.", "读书。") 
#r("Yi-la", "伊拉") #r("'veh-dan", "勿但") #r("zeh-ke", "是") #r("dok-su,", "读书，") #r("r-tshia", "而且") #r("'a", "也") #r("'auh", "学") #r("ok-li-kuh", "屋里个") #r("sang-weh.", "生活。") 

#r("La", "拉") #r("tsau-zung-deu,", "早晨头，") #r("lok", "六") #r("tien-tsoong", "点钟") #r("chi-sung,", "起身，") #r("kha-kha", "汏汏") #r("mien", "面") #r("lau", "咾") #r("s-ts", "梳之") #r("deu", "头") #r("meh,", "末，") #r("yeu-kuh", "有个") #r("ba", "排") #r("de-ts,", "檯子，") #r("yeu-kuh", "有个") #r("sau", "烧") #r("tsau-van.", "早饭。") #r("Tshih", "七") #r("tien-tsoong", "点钟") #r("chuh-hau-ts", "吃好之") #r("tsau-van,", "早饭，") #r("kauh", "各") #r("nyung", "人") #r("tsoo", "做") #r("pha-ding", "派定") #r("la-kuh", "拉个") #r("sang-weh;", "生活；") #r("ih-kuh", "一个") #r("nyung", "人") #r("meh", "末") #r("kha", "揩") #r("de-ts,", "檯子，") #r("ih-kuh", "一个") #r("nyung", "人") #r("meh,", "末") #r("sau", "扫") #r("di,", "地，") #r("ih-kuh", "一个") #r("nyung", "人") #r("meh,", "末") #r("daung", "盪") #r("wen", "碗") #r("lau", "咾") #r("da", "汏") #r("kwhan.", "筷。") #r("Tsoo", "做") #r("hau-ts", "好之") #r("di-kuh", "第个") #r("sang-weh,", "生活，") #r("sau-we", "稍为") #r("yeu", "有") #r("tien", "点") #r("koong-foo", "功夫") #r("khau-i", "可以") #r("beh-siang,", "勃相") #r("'ok-tse", "或者") #r("thi-tshau.", "体操。")#footnote[Physical drill.]

#r("Ngoo", "我") #r("siang", "想") #r("'auh-daung", "学堂") #r("li", "里") #r("yeu", "有") #r("di-kuh", "第个") #r("kwen-kyui", "规矩") #r("z", "是") #r("ting", "顶") #r("hau,", "好，") #r("iung-we", "因为") #r("siau-tsia", "小姐") #r("'veh-dan", "勿但") #r("we-tuh", "会得") #r("dok-su,", "读书，") #r("'a", "也") #r("we-tuh", "会得") #r("'auh", "学") #r("tsoo", "做") #r("ok-li-kuh", "屋里个") #r("sang-weh.", "生活。") #r("Dzoong", "从") #r("zien-kuh", "前个") #r("siau-tsia", "小姐") #r("dok-su-kuh", "读书个") #r("sau.", "少。") #r("Yeu", "有") #r("doong-dien-kuh", "铜钱个") #r("nyung-ka-kuh", "人家个") #r("siau-tsia", "小姐") #r("'a", "也") #r("'veh", "勿") #r("'auh", "学") #r("tsoo", "做") #r("ok-li-kuh", "屋里个") #r("sang-weh,", "生活，") #r("soo-i", "所以") #r("yeu", "有") #r("too-hau", "多化") #r("siau-tsia", "小姐") #r("ih-kuh", "一个") #r("z", "字") #r("'a", "也") #r("'veh", "勿") #r("suh,", "识，") #r("ok-li-kuh", "屋里个") #r("sang-weh", "生活") #r("ih-yang", "一样") #r("'a", "也") #r("'veh", "勿") #r("we", "会") #r("tsoo.", "做。") #r("Dan-z", "但是") #r("ok-li-kuh", "屋里个") #r("sang-weh", "生活") #r("z", "是") #r("nyui-nyung", "女人") #r("ba-veh-tuh-kuh", "罢勿得个") #r("z-thi.", "事体。")#footnote[Indispensable.] #r("Zak-zen", "若然") #r("siau-tsia", "小姐") #r("ih-ngan", "一颜") #r("'veh", "勿") #r("hyau-tuh", "晓得") #r("tsoo", "做") #r("sa", "啥") #r("meh,", "末，") #r("'eu-le", "后来") #r("yi", "伊") #r("'veh", "勿") #r("nung", "能") #r("ban-li", "办理") #r("ok-li-kuh", "屋里个") #r("z-thi,", "事体，") #r("soo-i", "所以") #r("nyung-ka", "人家") #r("'veh-lung", "勿论") #r("yeu", "有") #r("doong-dien", "铜钱") #r("lau", "咾") #r("m-meh", "无") #r("doong-dien", "铜钱") #r("zen", "全") #r("iung-ke", "应该") #r("kyau-hyuin", "教训") #r("yi-kuh", "伊个") #r("siau-tsia", "小姐") #r("dok-su", "读书") #r("lau", "咾") #r("tsoo", "做") #r("ok-li-kuh", "屋里个") #r("sang-weh.", "生活。") 

#r("Thaung-zen", "倘然") #r("siau-tsia", "小姐") #r("ka-tsheh-chi,", "嫁出去，") #r("van", "饭") #r("'a-'veh-we", "也勿会") #r("sau,", "烧，") #r("i-zaung", "衣裳") #r("'a", "也") #r("'veh-we", "勿会") #r("tsoo,", "做，") #r("ih-tshih-kuh", "一切个") #r("ling-se", "零碎") #r("sang-weh", "生活") #r("'a", "也") #r("tsoo-'veh-le,", "做勿来，") #r("zeh-ke", "实在") #r("yang-suh", "样式") #r("zeh-dze", "实在") #r("z", "是") #r("doo", "大") #r("'veh", "勿") #r("bien-taung,", "便当，") #r("r-tshia", "而且") #r("'eu-le", "后来") #r("yeu-ts", "有之") #r("r", "儿") #r("nyui", "女") #r("'a", "也") #r("'veh-nung-keu", "勿能彀") #r("kyau-hyuin", "教训") #r("yi-la.", "伊拉。") #r("Zeh-ke", "实在") #r("khoen-chi-le", "看起来") #r("siau-tsia", "小姐") #r("dok-su", "读书") #r("lau", "咾") #r("tsoo", "做") #r("sang-weh,", "生活，") #r("'veh-dan", "勿但") #r("z-ka", "自家") #r("tuh-dzak", "得着") #r("hau-tshu", "好处，") #r("'eu-deu", "后头") #r("kuh", "个") #r("nyung", "人") #r("'a", "也") #r("tuh-dzak", "得着") #r("iuh-tshu", "益处") #r("yan.", "也。")
