#import "../../template.typ": exercise, r

#exercise(60, "论救火个法则", "LUNG KYEU HOO KUH FAH-TSUH")

#r("Tsoong-kok", "中国") #r("zok", "俗语") #r("nyui", " ") #r("wo", "话") #r("(1)", " ") #r("\"S", "“水火") #r("hoo", " ") #r("'veh", "勿让") #r("nyang", " ") #r("nyung,\"", "人，”")#footnote[Water and fire do not regard man.] #r("pih-koo", "不过") #r("yien-dze", "现在") #r("iau", "要") #r("nau", "拿") #r("hoo-dzak", "火焑") #r("lau", "咾") #r("kyeu-hoo-kuh", "救火个") #r("z-thi", "事体") #r("kaung", "讲") #r("la", "拉") #r("na", "哪") #r("tsu-we", "诸位") #r("thing.", "听。") 
#r("Hoo-dzak", "火焑") #r("da-ke", "大概") #r("z", "是") #r("dzoong", "从") #r("sau-van", "烧饭") #r("'veh", "勿") #r("taung-sing,", "当心") #r("'ok-tse", "或者") #r("ya", "夜里") #r("li", " ") #r("kwhung-ts,", "睏之") #r("tung-hoo", "灯火") #r("'veh", "勿") #r("taung-sing,", "当心") #r("'a", "也有") #r("yeu", " ") #r("(2)", " ") #r("pau-hyien", "保险")#footnote[Insurance Co.] #r("la", "拉个") #r("kuh", " ") #r("tien-ka", "店家") #r("we-ts", "为之") #r("zeh-pung", "拆本") #r("lau", "咾") #r("(3)", " ") #r("faung-hoo", "放火")#footnote[Larceny.] #r("kuh,", "个，") #r("'a", "也") #r("'veh-sau.", "勿少。") 

#r("Zak-s", "若使") #r("noong", "侬") #r("tung", "登拉") #r("la", " ") #r("Zaung-he,", "上海") #r("tsho-'veh-too", "差勿多") #r("me", "每夜") #r("ya", " ") #r("khau-i", "可以") #r("thing-tuh", "听得") #r("khau", "敲") #r("(4)", " ") #r("hoo-tsoong,", "火钟。")#footnote[Fire bell.] #r("iung-we", "因为") #r("Zaung-he", "上海") #r("tah", "搭") #r("bih", "别个") #r("kuh", " ") #r("di-faung", "地方") #r("liang-yang", "两样") #r("kuh.", "个。") #r("Zak-zen", "若然") #r("la", "拉") #r("tsoo-ka", "租界里") #r("li", " ") #r("yeu", "有啥") #r("sa", " ") #r("hoo-dzak", "火焑") #r("meh,", "末") #r("zieu", "就敲") #r("khau", " ") #r("hoo-tsoong,", "火钟") #r("iau", "要") #r("peh", "拨") #r("kyeu-hoo-kwen", "救火管") #r("hyau-tuh", "晓得") #r("sa", "啥地方") #r("di-faung", " ") #r("hoo-dzak", "火焑") #r("lau", "咾") #r("ta", "带") #r("(5)", " ") #r("yang-loong", "洋龙")#footnote[Fire engine.] #r("tsheh-chi", "出去") #r("kyeu-hoo.", "救火。") 

#r("La", "拉") #r("Tsoo-ka", "租界上") #r("laung", " ") #r("kuh", "个") #r("mo-loo", "马路") #r("z", "是") #r("kwaung-kwhen,", "广阔，") #r("dzing-boo", "巡捕") #r("meh", "末") #r("too,", "多") #r("soo-i", "所以") #r("ih", "一听") #r("thing", " ") #r("hoo-tsoong", "火钟") #r("khau-ts", "敲") #r("kyi", "之") #r("kyi", "几记") #r("meh,", "末") #r("dzing-boo", "巡捕") #r("zieu", "就去") #r("chi", " ") #r("kwen-hau", "管好") #r("hoo-dzak", "火焑") #r("kuh", "个") #r("di-faung,", "地方") #r("mien-theh", "免脱") #r("nyung", "人") #r("(6)", " ") #r("tshiang-hoo.", "抢火。")#footnote[To steal.] #r("Yang-loong", "洋龙") #r("meh", "末") #r("yoong", "用") #r("mo,", "马") #r("'ok-tse", "或者") #r("yoong", "用") #r("kyi-chi", "机器") #r("'ang", "行") #r("kuh,", "个") #r("keh-lau", "盖咾") #r("'veh", "勿多") #r("too", " ") #r("ih", "一歇") #r("hyih,", " ") #r("zieu", "就会") #r("we", " ") #r("tau", "到") #r("hoo-dzak", "火焑场") #r("dzang", " ") #r("laung,", "上。") #r("nau", "拿") #r("(1)", " ") #r("bi-ta", "皮带")#footnote[Hose.] #r("tshih", "接") #r("la", "拉") #r("z-le-s", "自来水") #r("(2)", " ") #r("kwen-ts", "管子")#footnote[Water pipe.] #r("laung", "上") #r("lau", "咾") #r("zieu", "就好") #r("hau", " ") #r("kyeu-hoo", "救火") #r("kuh.", "个。") 

#r("Khau-sih", "可惜") #r("la", "拉") #r("Tsoong-kok", "中国") #r("di-ka", "地界") #r("m-meh", "无没") #r("zeh-ke", "实在") #r("kuh", "个") #r("kwha,", "快。") #r("iung-we", "因为") #r("la", "拉") #r("Tsoong-kok", "中国") #r("di-ka", "地界") #r("yoong", "用") #r("nyung", "人") #r("khau", "敲") #r("kyung-loo", "金锣") #r("pau", "报") #r("la", "拉") #r("yeu", "有") #r("yang-loong", "洋龙") #r("kuh", "个") #r("di-faung", "地方") #r("'veh-dan", "勿但") #r("zeh-ke", "实在") #r("man,", "是慢") #r("r-tshia", "而且") #r("ka-loo", "街路") #r("'a", "也") #r("'ah-tsah,", "狭窄，") #r("soo-i", "所以") #r("kung-ka", "更加") #r("van-nan;", "烦难。") #r("tung", "等到") #r("tau", " ") #r("yang-loong", "洋龙") #r("tau", "到") #r("meh,", "末") #r("vaung-ts", "房子") #r("i-kyung", "已经") #r("(3)", " ") #r("dzak-theh-ts", "焑脱之")#footnote[Burnt.] #r("kyi", "几间") #r("kan", " ") #r("tse.", "哉。") 

#r("La", "拉") #r("Zaung-he", "上海") #r("dzung", "城里") #r("li", " ") #r("wan", "还") #r("hau,", "好") #r("iung-we", "因为") #r("yeu", "有") #r("z-le-s", "自来水") #r("hau", "好") #r("yoong.", "用。") #r("La", "拉") #r("(4)", " ") #r("nen-di", "内地")#footnote[Interior.] #r("li", "里") #r("lau", "咾") #r("bih-kuh", "别个") #r("di-faung,", "地方") #r("yi-la", "伊拉") #r("kyeu-hoo", "救火") #r("kung-ka", "更加") #r("man,", "慢，") #r("we-ts", "为之") #r("m-meh", "无没") #r("z-le-s", "自来水") #r("lau", "咾") #r("iau", "要") #r("yoong", "用") #r("too-hau", "多化") #r("nyung", "人") #r("tau", "到") #r("pang", "浜里") #r("li", " ") #r("thiau", "挑") #r("s", "水") #r("(5)", " ") #r("tau", "倒拉")#footnote[Pour.] #r("la", " ") #r("yang-loong", "洋龙") #r("li", "里") #r("(6)", " ") #r("chung-tsheh-le-kuh,", "揎出来个")#footnote[Pump out.] #r("soo-i", "所以") #r("kung-ka", "更加") #r("kauh-dzak", "觉着") #r("man.", "慢。") #r("Zak-zen", "若然") #r("'oo", "河") #r("li-khe", "离开") #r("hoo-dzak-kuh", "火焑个") #r("dzang-hau", "场化") #r("yoen,", "远") #r("'ok-tse", "或者") #r("m-meh", "无没") #r("s", "水") #r("meh,", "末") #r("tsuh-hau", "只好") #r("nyang", "让他") #r("vaung-ts", "房子") #r("sau.", "烧。") 

#r("Ziang", "像") #r("la", "拉") #r("kyung", "今年") #r("nyien", " ") #r("Soo-tseu", "苏州") #r("dzung", "城里") #r("li", " ") #r("doo", "大") #r("hoo-dzak,", "火焑") #r("z", "是") #r("we-ts", "为之") #r("yang-loong", "洋龙") #r("meh", "末") #r("man,", "慢，") #r("s", "水") #r("meh", "末") #r("(7)", " ") #r("choeh-sau,", "缺少")#footnote[Lacking.] #r("keh-lau", "盖咾") #r("vaung-ts", "房子") #r("dzak-tuh", "焑脱") #r("zeh-ke", "实在") #r("too.", "是多。") 

#r("Tsau", "照") #r("ngoo", "我") #r("siang-chi-le", "想起来") #r("Tsoong-kok", "中国") #r("kauh-tshu", "各处") #r("di-faung", "地方") #r("iung-ke", "应该") #r("(8)", " ") #r("seh-lih", "设立")#footnote[Establish.] #r("z-le-s", "自来水") #r("koong-s", "公司") #r("lau", "咾") #r("khe", "开阔") #r("khweh", " ") #r("ka-dau.", "街道。") #r("Zeh-ke", "实在") #r("tsoo", "做") #r("meh,", "末") #r("soe-zen", "虽然") #r("yeu", "有") #r("hoo-dzak,", "火焑") #r("'a", "也") #r("'veh-we", "勿会") #r("zeu", "受") #r("yi-kuh", "伊个") #r("doo", "大") #r("'e-tse.", "害哉。")
