#import "../../template.typ": r, exercise

#exercise(64, "论流氓", "LUNG LIEU-MAUNG")

#r("LUNG", "论") #r("LIEU-MAUNG.", "流氓。") #r("Jung-le", "近来") #r("la", "拉") #r("Zaung-he", "上海") #r("tsoo-ka", "租界") #r("li,", "里") #r("lieu-maung", "流氓") #r("zeh-zen", "实在") #r("too", "多") #r("tuh-juh,", "得极") #r("r-tshia", "而且") #r("man", "蛮") #r("hyoong.", "凶。") #r("Yi-la", "伊拉") #r("ih-ngan", "一颜") #r("'veh", "弗") #r("pho", "怕") #r("chuh", "吃") #r("kwen-s.", "官司。")#footnote[To have a law suit.] 

#r("Ngoo", "我") #r("la", "拉") #r("sing-vung-ts", "新闻纸") #r("laung", "上") #r("dzang-tsaung", "常庄") #r("khoen-kyien", "看见") #r("yeu", "有") #r("lieu-maung", "流氓") #r("tshak-sau", "拆梢")#footnote[To steal.] #r("lau,", "咾") #r("tshok-sah", "觸杀")#footnote[To stab.] #r("nyung", "人") #r("kuh", "个") #r("z-thi.", "事体。") #r("Di-kuh", "第个") #r("nyoeh", "月") #r("tshoo", "初") #r("kyeu,", "九") #r("yeu", "有") #r("ih-kuh", "一个") #r("tsieu-tien", "酒店") #r("li", "里") #r("tsoo", "做") #r("tsang-vaung-kuh", "账房个") #r("nyung,", "人") #r("tseu", "走") #r("koo", "过") #r("San-si-loo-kuh", "山西路个") #r("ih-diau", "一条") #r("loong-daung", "街堂")#footnote[Alleyway.] #r("li,", "里") #r("bang-dzak", "碰着") #r("ih-kuh", "一个") #r("ta", "带") #r("tau-kuh", "刀个") #r("lieu-maung.", "流氓。") 

#r("Di-kuh", "第个") #r("lieu-maung", "流氓") #r("yoong", "用") #r("tau", "刀") #r("hak", "吓") #r("yi", "伊") #r("lau", "咾") #r("mung", "问") #r("yi", "伊") #r("tsia", "借") #r("yang-dien,", "洋钱") #r("dan-z", "但是") #r("yi", "伊") #r("'veh", "弗") #r("khung", "肯") #r("tsia", "借") #r("la", "拉") #r("yi,", "伊") #r("soo-i", "所以") #r("di-kuh", "第个") #r("hyoong-kuh", "凶个") #r("lieu-maung,", "流氓") #r("tshok-saung", "觸伤") #r("yi-kuh", "伊个") #r("'oo-loong,", "喉嚨")#footnote[Throat.] #r("pok-theh", "剥脱")#footnote[Strip off.] #r("yi", "伊") #r("yeu", "有") #r("hyoeh-tsih-kuh", "血跡个")#footnote[Blood stained.] #r("mo-kwo", "马褂")#footnote[Cloak.] #r("lau,", "咾") #r("dau-tseu-tse.", "逃走哉。") 

#r("Nan-meh", "难末") #r("zeu", "受") #r("saung-kuh", "伤个") #r("nyung,", "人") #r("zoo-ts", "坐之") #r("toong-yang-tsho,", "东洋车") #r("tau", "到") #r("zing-boo-vaung", "巡捕房") #r("li", "里") #r("chi", "去") #r("kau-zaung.", "告状。") #r("Sia-z-kan", "写字间") #r("li", "里") #r("kuh", "个") #r("san-da-deu", "三逮头") #r("mung", "问") #r("tshing-saung-ts", "清爽之") #r("yi", "伊") #r("soo", "所") #r("kau-kuh", "告个") #r("z-thi,", "事体") #r("lih-khuh", "立刻") #r("tsha", "差") #r("pau-tang-thing", "包打听") #r("tau", "到") #r("San-si-loo", "山西路") #r("chi", "去") #r("tang-thing,", "打听") #r("'a", "也") #r("kyau", "叫") #r("ih-kuh", "一个") #r("dzing-boo", "巡捕") #r("soong", "送") #r("di-kuh", "第个") #r("zeu", "受") #r("saung-kuh", "伤个") #r("nyung,", "人") #r("tau", "到") #r("Mak-ka-choen", "麦家圈") #r("bing-vaung", "病房")#footnote[London mission hospital.] #r("li", "里") #r("chi.", "去。") 

#r("Yien-dze", "现在") #r("pau-tang-thing", "包打听") #r("i-kyung", "已经") #r("dzoong", "从") #r("tien-taung", "典当")#footnote[Pawn shop.] #r("li", "里") #r("tiau-tsheh", "吊出") #r("ih-jien", "一件") #r("yeu", "有") #r("hyoeh-tsih-kuh", "血跡个") #r("mo-kwo", "马褂") #r("lau,", "咾") #r("kau-soo", "告诉") #r("dzing-boo-deu,", "巡捕头") #r("soo-i", "所以") #r("dzing-boo-deu", "巡捕头") #r("tshing", "请") #r("Sing-nga-mung-kuh", "新衙门个") #r("lau-ya,", "老爷") #r("tsheh", "出") #r("dze-tan", "传单")#footnote[Summons.] #r("chi", "去") #r("dze", "传") #r("tien-taung", "典当") #r("kuh", "个") #r("lau", "老") #r("pan", "班") #r("le,", "来") #r("iung-we", "因为") #r("yi", "伊") #r("seu-ts", "收之") #r("yeu", "有") #r("hyoeh-tsih-kuh", "血跡个") #r("mo-kwo", "马褂") #r("lau,", "咾") #r("van", "犯") #r("tsoo-ka", "租界") #r("kuh", "个") #r("tsang-zung", "章程")#footnote[Rules.] #r("yan.", "也。") 

#r("Zaung-he", "上海") #r("saung-'oo", "商务") #r("tsoong-we-kuh", "总会个")#footnote[Chamber of commerce.] #r("toong-z,", "董事")#footnote[Manager.] #r("'a", "也") #r("fan-te", "反对") #r("i", "伊") #r("ban-tien-taung", "爿典当") #r("seu", "收") #r("taung", "当") #r("yeu", "有") #r("hyoeh", "血") #r("tsih", "跡") #r("kuh", "个") #r("mo-kwo", "马褂") #r("lau,", "咾") #r("da-ka", "大家") #r("saung-liang", "商量") #r("yoong", "用") #r("hau-kuh", "好个") #r("fah-tsuh", "法则") #r("kyung-theh", "禁脱") #r("tien-taung-seu", "典当收") #r("zuh-tsaung.", "贼赃。")#footnote[Stolen things.]
