#import "../../template.typ": exercise, r

#exercise(65, "论脚踏车", "LUNG KYAK-DAH-TSHO")

#r("LUNG", "论") #r("KYAK-DAH-TSHO.", "脚踏车。") #r("Kyak-dah-tsho,", "脚踏车") #r("nyi", "伲") #r("Tsoong-kok", "中国") #r("pung-le", "本来") #r("z", "是") #r("m-meh", "无没") #r("kuh.", "个。") #r("'Eu-le", "后来") #r("nga", "外") #r("kok", "国") #r("nyung", "人") #r("nyung", " ") #r("tau-ts", "到之") #r("meh,", "末") #r("di-kuh", "第个") #r("kyak-dah-tsho", "脚踏车") #r("zieu", "就") #r("'ang-tau", "行到") #r("Tsoong-kok", "中国") #r("tse.", "哉。") #r("Soo-i", "所以") #r("yien-dze", "现在") #r("la", "拉") #r("Zaung-he", "上海") #r("di", "地") #r("faung", "方") #r("kyak-dah-tsho", "脚踏车") #r("lau", "咾") #r("khe", "开") #r("kyak-dah-tsho", "脚踏车") #r("tien-kuh", "店个") #r("z", "是") #r("man", "蛮") #r("too.", "多。") 

#r("Kyak-dah-tsho,", "脚踏车") #r("we", "会") #r("dah", "踏") #r("kuh", "个") #r("meh,", "末") #r("yeu", "有") #r("too", "多") #r("hau", "化") #r("bien-taung.", "便当。") #r("Ih-yang", "一样") #r("meh,", "末") #r("hau", "好") #r("sang", "省")#footnote[Save.] #r("doong-dien.", "铜钱。") #r("Di", "第") #r("nyi-yang", "二样") #r("meh,", "末") #r("'veh-lung", "勿论") #r("tau", "到") #r("sa", "啥") #r("di-faung", "地方") #r("chi,", "去") #r("z", "是") #r("kwha", "快") #r("lau", "咾") #r("z-'eu", "时候") #r("sau.", "少。") 

#r("Zak-zen", "若然") #r("zoo-ts", "坐之") #r("toong-yang-tsho,", "东洋车") #r("'ok-tse", "或者") #r("mo-tsho,", "马车") #r("'veh", "勿") #r("dan-z", "但是") #r("iau", "要") #r("yoong-theh", "用脱") #r("doong-dien,", "铜钱") #r("r-tshai", "而且") #r("'a", "也") #r("man-kuh.", "慢个。") 

#r("Kyak-dah-tsho", "脚踏车") #r("'a", "也") #r("yeu", "有") #r("kyi-yang", "几样") #r("'e-tshu,", "害处，") #r("zak-s", "若使") #r("'veh", "勿") #r("lieu-sing", "留心") #r("lau", "咾") #r("dzaung-tau-ts", "撞倒之") #r("nyung,", "人") #r("'ok-tse", "或者") #r("wa-theh-ts", "坏脱之") #r("bih-nyung-ka-kuh", "别人家个") #r("tsho-ts", "车子") #r("meh,", "末") #r("zieu", "就") #r("iau", "要") #r("siang-mo", "相骂")#footnote[Mutual quarreling.] #r("lau", "咾") #r("ben-wan", "赔还") #r("doong-dien,", "铜钱") #r("'veh", "勿") #r("zen", "然") #r("meh,", "末") #r("da-ka", "大家") #r("iau", "要") #r("nyieu-tau", "扭到")#footnote[Button hole, i. e. lead.] #r("dzing-boo-vaung", "巡捕房") #r("li", "里") #r("chi", "去") #r("kuh.", "个。") 

#r("Zak-zen", "若然") #r("iau", "要") #r("bi-theh", "避脱") #r("zaung-deu", "上头") #r("soo", "所") #r("wo-kuh", "话个") #r("nan-tshu", "难处") #r("meh,", "末") #r("pih", "必") #r("sui", "须") #r("'auh-le", "学来") #r("tsing-ming,", "精明")#footnote[Learn perfectly.] #r("zen-r", "然而") #r("'auh-kuh", "学个") #r("zung-kwaung,", "辰光") #r("pih-ding", "必定") #r("iau", "要") #r("chuh", "吃") #r("tien", "点") #r("khoo,", "苦") #r("'ok-tse", "或者") #r("gwan", "轧") #r("thoong,", "痛") #r("'ok-tse", "或者") #r("tsho-ts", "车子") #r("gwan-wa,", "损坏") #r("'veh-zen", "勿然") #r("meh,", "末") #r("tsoong", "总") #r("'auh", "学") #r("'veh", "勿") #r("dzung-koong", "成功") #r("kuh.", "个。")
