#import "../../template.typ": exercise, r

#exercise(66, "论忤逆爷娘", "LUNG NG-NYUH YA-NYANG")

#r("Tsau", "照") #r("Tsoong-kok", "中国") #r("kwen-kyui", "规矩")  #r("siau-pen", "小辈") #r("iung-ke", "应该") #r("thing", "听")  #r("tsang-pen", "长辈") #r("kuh", "个") #r("kyau-hyuung.", "教训。") #r("Tsang-pen", "长辈") #r("khau-i", "可以")  #r("kwen", "管") #r("siau-pen.", "小辈。") #r("Zak-zen", "若然") #r("yi-la", "伊拉") #r("'veh", "勿") #r("hau", "好") #r("meh,", "末") #r("tsang-pen", "长辈") #r("khau-i", "可以") #r("tsuh-be", "责备") #r("yi-la.", "伊拉。") #r("Nyien-kyi", "年纪") #r("chung-kuh", "轻个") #r("nyung,", "人，") #r("iung-ke", "应该") #r("thing", "听") #r("ya-nyang-kuh", "爷娘个") #r("kyau-hyuung,", "教训，") #r("ih-ngan", "一颜") #r("'a", "也") #r("'veh", "勿")  #r("we-be", "违背") #r("lau,", "咾，") #r("s-tuh", "使得") #r("yi-la", "伊拉") #r("dzang-tsaung", "常庄") #r("kha-weh", "快活") #r("lau", "咾") #r("'veh", "勿")  #r("ieu-dzeu.", "忧愁。") #r("Dzang-tsaung", "常庄") #r("taung-sing", "当心") #r("yi-la,", "伊拉，") #r("peh", "拨") #r("yi-la", "伊拉") #r("chuh-pau", "吃饱") #r("lau", "咾") #r("tsak-noen.", "着暖。") #r("Zeh-ke-nung-kuh", "实在能个") #r("nyung", "人") #r("meh,", "末，") #r("kyau", "叫") #r("hyau-ts.", "孝子。") 

#r("Zak-zen", "若然") #r("'eu-ts", "儿子") #r("'veh-thing", "勿听") #r("ya-nyung", "爷娘") #r("kuh", "个")  #r("ming-ling,", "命令，")#footnote[Commands.] #r("'veh", "勿") #r("taung-sing", "当心") #r("yi-la,", "伊拉，") #r("tang", "打") #r("yi-la,", "伊拉，") #r("mo", "骂") #r("yi-la,", "伊拉，") #r("'veh", "勿") #r("taung", "当") #r("yi-la", "伊拉") #r("ya-nyang", "爷娘") #r("khoen-de,", "看待") #r("s-tuh", "使得") #r("yi-la", "伊拉") #r("dzang-dzang", "常常") #r("ieu-dzeu", "忧愁") #r("lau,", "咾，") #r("m-meh", "无末") #r("kha-weh", "快活") #r("kuh", "个") #r("nyih-kyak.", "日脚。") #r("Di-kuh-nung-kuh", "第个能个") #r("nyung", "人") #r("meh,", "末，") #r("kyau", "叫") #r("nyuh-ts.", "逆子。") 

#r("Pi-faung", "比方") #r("la", "拉") #r("Zaung-he", "上海")  #r("yoen", "县")#footnote[District.] #r("li", "里") #r("tsheh-ts", "出之") #r("ih-kuh", "一个") #r("hyau-ts,", "孝子，") #r("keh-meh", "盖末") #r("yoen-kwen", "县官") #r("khau-i", "可以") #r("dzoong", "从")  #r("zaung-s", "上司")#footnote[Higher officials.] #r("han-deu", "壗头") #r("tuh-dzak", "得着")  #r("tsiang-saung,", "奖赏")#footnote[Reward.] #r("'ok-tse", "或者") #r("meh,", "末，") #r("iau", "要") #r("sung-yi", "陞伊") #r("tsoo", "做") #r("doo", "大") #r("kwen-foo.", "官府。") #r("Dan-z,", "但是，") #r("zak-zen", "若然") #r("tsheh-ts", "出之") #r("ih-kuh", "一个") #r("nyuh-ts,", "逆子，") #r("keh-meh", "盖末") #r("yi", "伊") #r("iau", "要") #r("peh-la", "拨拉") #r("zaung-s", "上司") #r("kak-theh-kuh.", "革脱个。") #r("Iung-we", "因为") #r("yoen-kwen-kuh", "县官个") #r("ming-vung", "名分") #r("z", "是") #r("kwen", "管") #r("ih-yoen", "一县") #r("kuh", "个") #r("pak-sing,", "百姓，") #r("hau", "好") #r("meh,", "末，") #r("iau", "要") #r("tshung-tsan", "称赞") #r("yi-la,", "伊拉，") #r("'veh", "勿") #r("hau", "好") #r("meh,", "末，") #r("iau", "要") #r("vah", "罚") #r("yi-la.", "伊拉。") 

#r("La", "拉") #r("Kaung-si", "江西") #r("di-faung", "地方") #r("yeu", "有") #r("ih-kuh", "一个")  #r("sieu-dze,", "秀才，")#footnote[An B. A.] #r("yeu", "有") #r("liang-kuh", "两个") #r("'eu-ts,", "儿子，") #r("doo-kuh", "大个") #r("la", "拉") #r("Zaung-he", "上海") #r("dok-su,", "读书，") #r("siau-kuh", "小个") #r("la", "拉") #r("pung-di", "本地") #r("dok-su.", "读书。") 

#r("Doo-kuh", "大个") #r("la", "拉") #r("Zaung-he", "上海") #r("dok-su", "读书") #r("kuh", "个") #r("z-'eu", "时候")  #r("gah-dzak-ts", "轧着之")#footnote[Associate with.] #r("liang-kuh", "两个") #r("wa", "坏") #r("bang-yeu,", "朋友，") #r("yi-la", "伊拉") #r("mien-laung", "面上") #r("meh,", "末") #r("te", "对") #r("yi", "伊") #r("man", "蛮") #r("ts-kyi,", "知己，") #r("dan-z", "但是") #r("'en-li", "暗里") #r("la", "拉") #r("tang-soen", "打算") #r("na-nung", "那能")  #r("phien", "骗")#footnote[Cheat.] #r("yi-kuh", "伊个") #r("doong-dien.", "铜钱。") #r("Ih-nyih-ts", "一日") #r("yi-la", "儿子") #r("ling", "伊拉领") #r("yi", "伊") #r("tau", "到") #r("bau-mo-thing", "跑马厅") #r("chi", "去") #r("khoen", "看")  #r("thiau-pang,", "跳浜。")#footnote[Steeple chase.] 

#r("yi-la", "伊拉") #r("tseu", "走") #r("tau", "到") #r("tau", " ") #r("too-doong-dien-kuh", "赌铜钱个") #r("di-faung,", "地方。") #r("khoen-kyien", "看见") #r("ih-kuh", "一个") #r("nyung", "人") #r("yung-ts", "赢之") #r("too-hau", "多化") #r("yang-dien.", "洋钱。") #r("Yi", "伊") #r("khoen-kyien-ts", "看见之") #r("tau", "倒") #r("yeu", "有") #r("tien", "点") #r("tien", " ")  #r("ngan-nyih,", "眼热")#footnote[Hot eyes.] #r("'a", "也") #r("iau", "要") #r("siang", "想") #r("siang", " ") #r("too", "赌") #r("tse.", "哉。") #r("Yi-la", "伊拉") #r("te", "对") #r("yi", "伊") #r("wo,", "话") #r("tsh-di", "此地") #r("too", "赌") #r("doong-dien,", "铜钱") #r("'veh", "勿")  #r("koong-bing.", "公平。")#footnote[Just.] 

#r("'Eu-le", "后来") #r("yi-la", "伊拉") #r("ling-yi", "领伊") #r("tau", "到") #r("ih-ban", "一爿") #r("dzo-kwen", "茶馆") #r("li", "里") #r("chi", "去") #r("too.", "赌。") #r("Chi-deu", "起头") #r("yi", "伊") #r("yung-ts", "赢之") #r("ih-pak", "一百") #r("too", "多") #r("kwhe", "块") #r("yang-dien,", "洋钱。") #r("dan-z", "但是") #r("'eu-le,", "后来")  #r("kyung-ziang", "竟像")#footnote[The same as.] #r("jang-dau", "强盗") #r("tang-kwen-s", "打官司")  #r("tsuh-su", "只输") #r("'veh", "勿") #r("yung.", "赢。")#footnote[Only losing, no winning.] 

#r("Yi", "伊") #r("lien-laung", "连上") #r("too", "赌") #r("ts", "之") #r("san", "三") #r("nyih,", "日。") #r("too", "赌") #r("su-theh-ts", "输脱之") #r("ng-lok-pak", "五六百") #r("yang-dien.", "洋钱。") #r("Yi", "伊") #r("su-theh-la-kuh", "输脱拉个") #r("yang-dien,", "洋钱") #r("zen-z", "全是") #r("tan", "担") #r("z-ka", "自家") #r("kuh", "个") #r("i-zaung", "衣裳") #r("chi", "去") #r("taung-le-kuh.", "当来个。") 

#r("Liang-kuh", "两个") #r("wa", "坏") #r("bang-yeu", "朋友") #r("te", "对") #r("yi", "伊") #r("wo,", "话") #r("ting", "顶") #r("hau", "好") #r("meh,", "末") #r("noong", "侬") #r("tsen-chi", "转去") #r("tan", "担") #r("tien", "点") #r("yang-dien", "洋钱") #r("tsheh-le", "出来")  #r("fan", "反") #r("pung.", "本。")#footnote[Restore the original.] #r("Tau", "到") #r("'eu-seu-le,", "后首末") #r("yi", "伊") #r("chi", "去") #r("taung-theh-ts", "当脱之") #r("ih-tsak", "一只")  #r("kyung-kaung-tsuen", "金鋼鑽")#footnote[Diamond ring.] #r("ka-ts", "戒指") #r("lau", "咾") #r("zok-ts", "赎之") #r("tien", "点") #r("i-zaung,", "衣裳，") #r("ma-ts", "买之") #r("ih-tsang", "一张") #r("zen-phiau", "船票") #r("lau", "咾") #r("tsen-chi", "转去") #r("tse.", "哉。") 

#r("Tau-ts", "到之") #r("ok-li,", "屋里") #r("yi", "伊") #r("zieu", "就") #r("mung", "问") #r("ya", "爷") #r("thau", "讨") #r("yang-dien.", "洋钱。") #r("Ya", "爷") #r("mung", "问") #r("yi", "伊") #r("wo", "话") #r("sa", "啥") #r("yoong-deu.", "用头。") #r("Yi", "伊") #r("we-deu", "回头") #r("'veh-tsheh.", "勿出。") #r("Ya", "爷") #r("yi", "又") #r("mung", "问") #r("yi", "伊") #r("wo,", "话") #r("noong-kuh", "侬个") #r("ka-ts,", "戒指、")  #r("oo-khan", "狐嵌")#footnote[Fox skin gown.] #r("bau-ts", "袍子") #r("lau,", "咾")  #r("hwen-tshu", "灰鼠")#footnote[Squerrel skin cloak, Jacket.] #r("mo-kwo", "马褂") #r("tau", "到") #r("sa-di-faung", "啥地方") #r("chi-tse.", "去哉。") #r("Yi", "伊") #r("we-deu", "回头") #r("'veh", "勿") #r("tsheh", "出") #r("lau", "咾") #r("tseu-khe", "走开") #r("tse.", "哉。") 

#r("Tau-ts", "到之") #r("ya-li", "夜里") #r("pah", "八") #r("kyeu", "九") #r("tien-tsoong-kuh", "点钟个") #r("z-'eu,", "时候。") #r("yi", "伊") #r("bau", "跑") #r("tau", "到") #r("ya", "爷") #r("kuh", "个") #r("vaung-kan", "房间") #r("li", "里") #r("chi", "去")  #r("pih", "逼")#footnote[To press.] #r("yi", "伊") #r("peh", "拨") #r("yang-dien", "洋钱") #r("la", "拉") #r("yi.", "伊。") #r("Yi-kuh", "伊个")  #r("ya-sok", "爷叔")#footnote[Uncle.] #r("la", "拉") #r("kah-pih", "隔壁") #r("vaung", "房") #r("li", "里") #r("thing-kyien-ts,", "听见之") #r("zieu", "就") #r("koo-le", "过来") #r("tsauh-lau-ts", "捉牢之") #r("yi", "伊") #r("lau,", "咾")  #r("taung", "当") #r("ya", "夜")#footnote[That night.] #r("soong", "送") #r("yi", "伊") #r("tau", "到") #r("yoen-li.", "县里。") 

#r("Tau", "到") #r("ming-tsau", "明早") #r("lau-ya", "老爷")  #r("sung", "审")#footnote[Tried him.] #r("yi.", "伊，") #r("Yi", "伊") #r("ih-ngan", "一颜") #r("'veh", "勿") #r("khung-wo", "肯话") #r("sa.", "啥。") #r("Lau-ya", "老爷") #r("fung-foo", "吩咐") #r("kwan", "关") #r("yi", "伊") #r("la", "拉")  #r("ke-koo-jok", "改过局")#footnote[Reformatory.] #r("li", "里") #r("zeh-nyien", "十年") #r("koong-foo.", "功夫。")
