#import "../../template.typ": exercise, r

#exercise(41, "论一只狗", "LUNG IH-TSAK KEU")

#r("Ngoo", "我") #r("yeu", "有") #r("ih-tsak", "一只") #r("keu.", "狗。") 
#r("Di-tsak", "第只") #r("keu", "狗") #r("z", "是") #r("sing-kuh", "新个") #r("keu,", "狗，") #r("pih-koo", "不过") #r("yang-ts", "养之") #r("ih-nyien-too.", "一年多。") 
#r("Tsoong-chi", "种气")#footnote[Breed.] #r("z", "是") #r("man-doo-kuh,", "蛮大个，") 
#r("yi", "伊") #r("z", "是") #r("hyi-hwen", "喜欢") #r("beh-siang,", "勃相，") #r("'a", "也") #r("hyi-hwen", "喜欢") #r("tah-ts", "搭之") #r("dzoe-bien", "随便") #r("sa-nyung", "啥人") #r("loong-beh-siang.", "弄勃相。") 
#r("Chi-deu", "起头") #r("le-kuh", "来个") #r("zung-kwaung,", "辰光，") #r("yi", "伊") #r("iau", "要") #r("ngau", "咬") #r("nyung.", "人。") 
#r("Yi", "伊") #r("ngau-ts", "咬之") #r("meh", "末") #r("ngoo", "我") #r("zieu", "就") #r("tang", "打") #r("yi.", "伊。") 
#r("Soo-i", "所以") #r("yien-dze", "现在") #r("yi", "伊") #r("ih-ngan", "一颜") #r("'veh", "勿") #r("ngau-nyung,", "咬人，") 
#r("dan-z", "但是") #r("ngoo", "我") #r("siang-chi-le", "想起来") #r("yeu", "有") #r("zuh", "贼") #r("le", "来") #r("meh,", "末，") #r("yi", "伊") #r("pih-ding", "必定") #r("iau", "要") #r("ngau-kuh.", "咬个。") 
#r("Yi", "伊") #r("baung-ya", "防夜")#footnote[Watch at night.] #r("z", "是") #r("man-hau-kuh;", "蛮好个；") 
#r("zak-zen", "若然") #r("yeu", "有") #r("sa-nyung", "啥人") #r("le,", "来，") #r("yi", "伊") #r("ih-ding", "一定") #r("iau", "要") #r("ngau-kuh.", "咬个。") 
#r("R-tshia", "而且") #r("di-tsak", "第只") #r("keu", "狗") #r("z", "是") #r("man-tshoong-ming-kuh.", "蛮聪明个。") 
#r("Ngoo", "我") #r("tsen-le-kuh", "转来个") #r("zung-kwaung", "辰光") #r("iau", "要") #r("kyau", "教") #r("yi", "伊") #r("nau", "拿") #r("thoo-a", "拖鞋") #r("le,", "来，") #r("yi", "伊") #r("we", "会") #r("'an-le-kuh.", "嘟来个。") 
#r("khoen-kyien", "看见") #r("ngoo", "我") #r("iau", "要") #r("tsheh-chi", "出去") #r("meh,", "末，") #r("yi", "伊") #r("'an-ts", "嘟之") #r("ts-thau", "嘴套")#footnote[Muzzle.] #r("le,", "来，") #r("iau", "要") #r("ngoo", "我") #r("tah", "搭") #r("yi", "伊") #r("thau-ts", "套之") #r("lau,", "咾，") #r("ling", "领") #r("yi", "伊") #r("tsheh-chi.", "出去。") 
#r("Ngoo", "我") #r("ling", "领") #r("yi", "伊") #r("tsheh-chi,", "出去，") #r("iau", "要") #r("khuh-khuh", "刻刻") #r("lieu-sing", "留心") #r("yi,", "伊，") 
#r("iung-we", "因为") #r("yi", "伊") #r("dzoe-bien", "随便") #r("tau", "到") #r("sa", "啥") #r("'oo-daung", "户荡") #r("bau,", "跑，") #r("'veh", "勿") #r("khung", "肯") #r("la", "拉") #r("ngoo", "我") #r("'eu-deu", "后头") #r("tseu-kuh.", "走个。") 
#r("La", "拉") #r("mo-loo", "马路") #r("laung", "上") #r("iau", "要") #r("zah-le", "闹来") #r("zah-chi,", "闹去。") 
#r("bau", "跑") #r("tau", "到") #r("nyung-ka", "人家") #r("tien", "店") #r("li", "里") #r("chi", "去") #r("khoen-khoen;", "看看；") 
#r("khoen-kyien-ts", "看见之") #r("mo-tsho", "马车") #r("lau-sa,", "咾啥，") #r("iau", "要") #r("kung", "跟") #r("yi", "伊") #r("lau", "咾") #r("bau.", "跑。")

#r("Zaung", "上") #r("kuh", "个") #r("li-pa-nyih", "礼拜日") #r("tsau-zung-deu", "早晨头") #r("ngoo", "我") #r("ling-ts", "领之") #r("yi", "伊") #r("tsheh-chi", "出去") #r("bau", "跑") #r("beh-siang,", "勃相，") 
#r("yi", "伊") #r("khoen-kyien", "看见") #r("ih-kuh", "一个") #r("nyung", "人") #r("zoo-ts", "坐之") #r("kyak-dah-tsho", "脚踏车") #r("lau", "咾") #r("tseu,", "走，") #r("yi", "伊") #r("tau", "倒") #r("tsoe", "追") #r("yi,", "伊，") #r("tsoe-tau", "追到") #r("kyak-dah-tsho", "脚踏车") #r("han-deu.", "壗头。") 
#r("Yi", "伊") #r("iau", "要") #r("thiau", "跳") #r("la", "拉") #r("nyung", "人") #r("sung-laung,", "身上，") #r("'a", "也") #r("iau", "要") #r("tseu", "走") #r("la", "拉") #r("yi-kuh", "伊个") #r("tsho-ts", "车子") #r("zien-deu", "前头") #r("kuh", "个") #r("loo-laung,", "路上，") 
#r("soo-i", "所以") #r("i-kuh-nyung", "伊个人") #r("'veh", "勿") #r("nung-keu", "能够") #r("tseu", "走") #r("lau,", "咾") #r("zieu", "就") #r("lok-ts", "趖") #r("'au-le.", "下来。") 
#r("Yi", "伊") #r("koo-chi", "过去") #r("ih-ngan,", "一颜，") #r("khoen-kyien-ts", "看见之") #r("ih-kuh", "一个") #r("siau-noen", "小囡") #r("la", "拉") #r("bau.", "跑。") 
#r("Yi", "伊") #r("iau", "要") #r("tah-ts", "搭之") #r("di-kuh", "第个") #r("siau-noen", "小囡") #r("beh-siang", "勃相") #r("lau,", "咾，") #r("soo-i", "所以") #r("tsoe", "追") #r("yi.", "伊。") 
#r("Siau-noen", "小囡") #r("hak-le-si,", "吓来死，") #r("ih-deu", "一头") #r("khok", "哭") #r("lau,", "咾，") #r("ih-deu", "一头") #r("bau.", "跑。") 
#r("Ngoo", "我") #r("zieu", "就") #r("han", "喊") #r("keu", "狗") #r("tse-le,", "转来，") #r("kyau", "教") #r("yi", "伊") #r("'veh", "勿") #r("iau", "要") #r("zeh-ke", "实盖") #r("yang-suh,", "样式，") 
#r("dan-z", "但是") #r("ngoo", "我") #r("siang-chi-le", "想起来") #r("'veh", "勿") #r("khung", "肯") #r("thing", "听") #r("ngoo", "我") #r("kuh", "个") #r("seh-wo,", "说话，") 
#r("iung-we", "因为") #r("hyih-ts", "歇之") #r("ih-hyih,", "一歇，") #r("yi", "伊") #r("khoen-kyien", "看见") #r("ih-tsak", "一只") #r("mau", "猫") #r("zoo", "坐") #r("la", "拉") #r("nyung-ka", "人家") #r("mung-kheu-deu,", "门口头，") #r("zieu", "就") #r("bau-zaung-chi", "跑上去") #r("hak", "吓") #r("di-tsak", "第只") #r("mau.", "猫。") 
#r("Dan-z", "但是") #r("di-tsak", "第只") #r("mau", "猫") #r("z", "是") #r("lau", "老") #r("mau", "猫") #r("'veh-pho", "勿怕") #r("ngoo", "我") #r("kuh", "个") #r("keu.", "狗。") 
#r("Yi-kuh", "伊个") #r("pe-sing", "背心") #r("kyok-chi-le,", "鞠起来，")#footnote[Kunch up its back.] #r("iau", "要") #r("siang", "想") #r("tah-ts", "搭之") #r("keu", "狗") #r("siang-teu", "相鬥")#footnote[Fight.] #r("tse;", "哉；") 
#r("keu", "狗") #r("zieu", "就") #r("lih-ding-ts", "立定之") #r("'veh-ke", "勿敢")#footnote[Dare not.] #r("tseu-zaung-chi-tse.", "走上去。") 
#r("Yi", "伊") #r("yoen-khe-ts", "远开之") #r("ih", "一") #r("ngan", "颜") #r("lau,", "咾，") #r("wa-la-wa-la", "唔拉唔拉")#footnote[To bawl, cry.] #r("ngau-chi", "咬起") #r("le-tse.", "来哉。")

#r("Ngoo", "我") #r("kuh", "个") #r("keu", "狗") #r("khoen-kyien-ts", "看见之") #r("bih-tsak", "别只") #r("keu,", "狗，") #r("yi", "伊") #r("tau", "倒") #r("tsoe-kuh;", "追个；") 
#r("khoen-kyien-ts", "看见之") #r("mo", "马") #r("yi", "伊") #r("iau", "要") #r("ngau-kuh.", "咬个。") 
#r("Iung-we", "因为") #r("zeh-ke,", "实盖") #r("na", "哪") #r("khau-i", "可以") #r("hyau-tuh", "晓得") #r("ngoo", "我") #r("ling", "领") #r("yi", "伊") #r("tsheh-chi", "出去") #r("kuh", "个") #r("zung-kwaung", "辰光") #r("z", "是") #r("kyau-kwan", "交关") #r("van-zeh,", "烦难，") 
#r("dan-z", "但是") #r("ngoo", "我") #r("siang", "想") #r("yi", "伊") #r("nyien-soo", "年数") #r("doo-ts", "大之") #r("meh,", "末，") #r("yi", "伊") #r("beh-siang", "勃相") #r("kuh", "个") #r("sing", "心") #r("khau-i", "可以") #r("ke", "改") #r("hau", "好") #r("tien-tse.", "点哉。")
