#import "../../template.typ": r, exercise

#exercise(62, "论扒窃", "LUNG BO-SEU")

#r("LUNG", "论") #r("BO-SEU.", "扒窃。")#footnote[Thief.] #r("Yeu", "有") #r("ih-ban", "一片") #r("sing", "新") #r("khe", "开") #r("yang-hoo", "洋货") #r("tien,", "店")#footnote[A variety store.] #r("sang-i", "生意") #r("z", "是") #r("man", "蛮") #r("hyung-waung.", "兴旺。")#footnote[Very prosperous.] #r("Ma-kuh", "买个") #r("nyung", "人") #r("gah-le-si.", "轧来死。") 

#r("Yeu", "有") #r("ih-kuh", "一个") #r("hyang-'au", "乡下") #r("nyung", "人") #r("chi", "去") #r("ma", "买") #r("yang-hoo,", "洋布")#footnote[Foreign cloth.] #r("yi", "伊") #r("kan-ts", "拣之")#footnote[Selected.] #r("kyi", "几") #r("yang", "样") #r("ngan-suh,", "颜色") #r("iau", "要") #r("ma", "买") #r("kuh,", "个，") #r("dan-z", "但是") #r("yi-kuh", "伊个") #r("yang-dien", "洋钱") #r("pau", "包") #r("la", "拉") #r("kyoen-deu", "绢头") #r("li", "里") #r("lau,", "咾") #r("pa", "摆") #r("la", "拉") #r("jui-de", "柜檯") #r("laung.", "上。")#footnote[The counter.] 

#r("La", "拉") #r("yi", "伊") #r("kan", "拣") #r("yang-poo", "洋布") #r("kuh", "个") #r("z-'eu,", "时候，") #r("peh", "拨") #r("la", "拉") #r("ih", "一") #r("kuh", "个") #r("tshoong-seu", "挑手")#footnote[A pickpocket, thief.] #r("theu-ts-chi-tse.", "偷之去哉。") #r("Tung", "等到") #r("tau", "到") #r("yi", "伊") #r("ma", "买") #r("hau-ts", "好之") #r("lau", "咾") #r("iau", "要") #r("foo", "付") #r("yang-dien", "洋钱") #r("meh,", "末") #r("yi", "伊") #r("kuh", "个") #r("seu-kyung-pau", "手巾包") #r("'veh", "勿") #r("khoen-kyien-tse.", "看见哉。") #r("Nan-meh", "难末") #r("yi", "伊") #r("m-tshui", "无趣") #r("tuh-juh", "得极")#footnote[Very unhappy.] #r("lau,", "咾") #r("mung", "问") #r("tien-li", "店里") #r("kuh", "个") #r("nyung", "人") #r("khoen-kyien", "看见") #r("va?", "唔。") 

#r("Yi-la", "伊拉") #r("wo,", "话") #r("nyung-too", "人多") #r("seu-zeh,", "手杂。")#footnote[Occupied.] #r("ngoo-nyi", "我伲") #r("maung-le-si,", "忙来死") #r("tsau-koo", "照顾") #r("'veh", "勿") #r("tau-ka,", "到家。")#footnote[Cannot look out for everything.] #r("noong", "侬") #r("we-sa", "为啥") #r("zeh-ke", "实盖") #r("'veh", "勿") #r("taung-sing.", "当心。") #r("Nan-meh", "难末") #r("yi", "伊") #r("m-sa", "无啥") #r("wo-deu.", "话头。") #r("Iung-we", "因为") #r("liau-tsauh", "料作")#footnote[Material.] #r("i-kyung", "已经") #r("tsien", "剪") #r("hau,", "好")#footnote[Cut off.] #r("'veh-khau-i", "勿可以") #r("the-wan,", "退还。")#footnote[Return.] #r("soo-i", "所以") #r("yi", "伊") #r("tau", "到") #r("bang-yeu", "朋友") #r("han-deu", "壗头") #r("tsia-yang-dien", "借洋钱") #r("le", "来") #r("ma-chi.", "买去。") 

#r("La", "拉") #r("Zaung-he", "上海") #r("zeh-ke", "实盖") #r("kuh", "个") #r("z-thi,", "事体") #r("dzang-tsaung", "常庄") #r("yeu", "有") #r("tuh", "得") #r("thing-kyien-kuh.", "听见个。") #r("Ih-kuh", "一个") #r("'veh", "勿") #r("lieu-sing", "留心")#footnote[To be careless for an instant.] #r("meh,", "末") #r("meh-z", "物事") #r("zieu", "就") #r("theu-ts-chi-tse.", "偷之去哉。") #r("Soo-i", "所以") #r("khak-pien", "客边") #r("nyung", "人")#footnote[A person from a neighboring region.] #r("kung-ka", "更加") #r("iau", "要") #r("kyung-zung.", "谨慎。")#footnote[Careful.] #r("Di-kuh", "第个") #r("hyang-'au", "乡下") #r("nyung", "人") #r("chuh-ts", "吃之") #r("ih", "一") #r("tsen-chui", "转亏") #r("meh,", "末")#footnote[Eat bitterness once.] #r("khau-i", "可以") #r("'auh", "学") #r("ih-tsen", "一转") #r("kwa", "乖") #r("tse.", "哉。")#footnote[Learn experience.]
