#import "../../template.typ": r, exercise

#exercise(68, "论卫生个法则", "LUNG-WE-SUNG-KUH FAH-TSUH")

#r("Zak-zen", "若然") #r("ih-kuh", "一个") #r("nyung", "人") #r("iau", "要") #r("sung-thi", "身体") #r("(3)", " ") #r("jang-jien", "强健")#footnote[Strong.] #r("meh,", "末") #r("tsoong", "总") #r("iau", "要") #r("tsung", "遵") #r("seu", "守") #r("we-sung", "卫生") #r("kuh", "个") #r("fah-tsuh.", "法则。") 

#r("Tsau", "照") #r("we-sung", "卫生") #r("kuh", "个") #r("fah-tsuh,", "法则") #r("koen-zing", "干净") #r("z", "是") #r("soen", "算") #r("ting", "顶") #r("iau-kyung-kuh.", "要紧个。") #r("Soo-i", "所以") #r("nyung-nyung", "人人") #r("iung-ke", "应该") #r("taung-sing,", "当心") #r("iung-we", "因为") #r("auh-tshauh", "龌龊") #r("z", "是") #r("sang-bing-kuh", "生病个") #r("kung-pung.", "根本。") #r("Ih-kuh", "一个") #r("nyung", "人") #r("me", "每") #r("nyih", "日") #r("iau", "要") #r("(4)", " ") #r("zing", "净") #r("ih-we", "一回") #r("yok,", "浴")#footnote[Take a bath.] #r("zing", "净") #r("hau-ts", "好之") #r("yok", "浴") #r("iau", "要") #r("yoong", "用") #r("koen", "乾") #r("seu-kyung", "手巾") #r("kha", "揩") #r("koen", "乾") #r("yi", "伊") #r("kuh", "个") #r("sung-thi,", "身体") #r("(5)", " ") #r("dzang-pho", "常怕")#footnote[For fear.] #r("sak-chi", "湿气") #r("iau", "要") #r("tau", "到") #r("(6)", " ") #r(" 'oen-mau", "汗毛") #r("kwen", "管")#footnote[Pores.] #r("li", "里") #r("chi-kuh,", "去个") #r("iung-we", "因为") #r("zing-yok", "净浴") #r("nung-keu", "能够") #r("s-tuh", "使得") #r("'oen-mau", "汗毛") #r("kwen", "管") #r("khe-le,", "开启来") #r("keh-meh", "盖末") #r("sung-thi", "身体") #r("li", "里") #r("kuh", "个") #r("(7)", " ") #r("fi-liau", "废料")#footnote[Waste of the body.] #r("khau-i", "可以") #r("dzoong", "从") #r("'oen-mau", "汗毛") #r("kwen", "管") #r("li", "里") #r("tsheh-le.", "出来。") 

#r("I-zaung", "衣裳") #r("lau", "咾") #r("bi-deu", "被头") #r("iung-ke", "应该") #r("dzang-tsaung", "常庄") #r("koeh-lih,", "渧渧") #r("thaung-zen", "倘然") #r("'veh", "勿") #r("koeh-li", "渧渧") #r("meh,", "末") #r("i-kuh", "伊个") #r("auh-tshauh", "龌龊") #r("iau", "要") #r("thah-le", "榻累") #r("sung-thi", "身体") #r("lau,", "咾") #r("suh-meh", "塞没") #r("'oen-mau", "汗毛") #r("kwen,", "管") #r("nan-meh", "难末") #r("nyung", "人") #r("iau", "要") #r("sang-bing", "生病") #r("tse.", "哉。") #r("Sak-kuh", "湿个") #r("di-faung", "地方") #r("'veh", "勿") #r("khau-i", "可以") #r("kwhung,", "睏") #r("sak-kuh", "湿个") #r("i-zaung", "衣裳") #r("'a", "也") #r("'veh", "勿") #r("khau-i", "可以") #r("tsak-kuh.", "着个。") 

#r("Di-'au-kuh", "地下个") #r("(1)", " ") #r("iung-keu", "阴沟")#footnote[A covered drain.] #r("dzang-tsaung", "常庄") #r("iung-ke", "应该") #r("(2)", " ") #r("lieu-thoong,", "流通")#footnote[Flush.] #r("thaung-zen", "倘然") #r("(3)", " ") #r("suh-meh-ts", "塞没之")#footnote[Stopped.] #r("meh,", "末") #r("i-kuh", "伊个") #r("auh-tshauh", "龌龊") #r("'veh", "勿") #r("nung-keu", "能够") #r("lieu-tsheh-chi", "流出去") #r("lau,", "咾") #r("'eu-le", "后来") #r("iau", "要") #r("sang-tsheh", "生出") #r("(4)", " ") #r("tsheu-chi-le,", "臭气来")#footnote[Foul air.] #r("nyung", "人") #r("mung-dzak-ts", "闻着之") #r("meh,", "末") #r("iau", "要") #r("sang-bing-kuh.", "生病个。") #r("Tshaung", "窗") #r("lau", "咾") #r("mung", "门") #r("'a", "也") #r("iau", "要") #r("dzang-tsaung", "常庄") #r("khe", "开") #r("la,", "拉") #r("keh-meh", "盖末") #r("nyung", "人") #r("khau-i", "可以") #r("(5)", " ") #r("hoo-hyih", "呼吸")#footnote[To breathe.] #r("tshing-saung-kuh", "清爽个") #r("khoong-chi.", "空气。") 

#r("Nyung", "人") #r("tsoong", "终") #r("'veh", "勿") #r("iau", "要") #r("too", "多") #r("chuh", "吃") #r("tsieu,", "酒") #r("iung-we", "因为") #r("tsieu", "酒") #r("iau", "要") #r("saung-wa", "伤坏") #r("nyung-kuh", "人个") #r("sung-thi.", "身体。") #r("Nyung", "人") #r("'a", "也") #r("'veh", "勿") #r("khau-i", "可以") #r("too", "多") #r("chuh", "吃") #r("'veh", "勿") #r("zung", "曾") #r("sau-koo-hyih-kuh", "烧过歇个") #r("s-koo.", "水果。") #r("Nyung", "人") #r("iung-ke", "应该") #r("chuh-kuh", "吃个") #r("z", "是") #r("(6)", " ") #r("soo-zing", "素净")#footnote[Clean vegetables.] #r("lau", "咾") #r("we", "会") #r("(7)", " ") #r("siau-hwo", "消化")#footnote[Digestable.] #r("kuh", "个") #r("meh-z,", "物事") #r("dan-z", "但是") #r("'veh", "勿") #r("iau", "要") #r("chuh-le", "吃来") #r("thuh", "忒") #r("pau,", "饱") #r("'a", "也") #r("'veh", "勿") #r("khau-i", "可以") #r("doo-li", "肚里") #r("ngoo.", "饿。") 
#r("(8)", " ") #r("Thi-tshau", "体操")#footnote[Physical drill.] #r("'a", "也") #r("z", "是") #r("iau-kyung-kuh,", "要紧个") #r("soo-i", "所以") #r("yeu-kuh", "有个") #r("nyung", "人") #r("la", "拉") #r("me-nyih", "每日") #r("tsau-zung-deu", "早晨头") #r("yoong", "用") #r("(9)", " ") #r("au-ling", "哑铃")#footnote[Dumb bells.] #r("tshau-lien", "操练") #r("yi-kuh", "伊个") #r("sung-thi.", "身体。")
