#import "../../template.typ": r, exercise

#exercise(58, "论四季", "LUNG S KYI")

#r("La", "拉") #r("s", "四季") #r("kyi", "当中") #r("taung-tsoong", "春天") #r("tshung", "是") #r("thien", "顶好") #r("z", "个") #r("ting", "天气") #r("hau", "因为") #r("kuh", "人人") #r("thien-chi,", "个") #r("we-ts", "身体") #r("nyung-nyung", "一定") #r("kuh", "觉着") #r("sung-thi", "蛮") #r("ih-ding", "爽快") #r("kauh-dzak", "花草") #r("(3) man-saung-kwha,", "树木")#footnote[Very well.] #r("hwo-tsau", "也是") #r("zu-mok", "长大") #r("'a", "发出") #r("z", "新鲜") #r("tsang", "个") #r("doo,", "香气") #r("fah-tsheh", "来") #r("sing-sien", "人人") #r("kuh", "闻着") #r("hyang-chi", "之") #r("le,", "末") #r("nyung-nyung", "蛮") #r("mung-dzak", "开心") #r("ts", "若然") #r("meh,", "叫") #r("man", "一只") #r("(4) khe-sing.", "船")#footnote[Happy, literally to open the heart.] 
#r("Zak-zen", "到") #r("kyau", "乡下") #r("ih", "去") #r("tsak", "看看") #r("zen", "春天") #r("tau", "个") #r("hyang-'au", "景致") #r("chi", "是") #r("khoen-khoen", "顶") #r("tshung-thien", "快活") #r("kuh", "个") #r("kyung-ts,", "勃相") #r("z-ting", "因为") #r("kha-weh", "每年") #r("kuh", "春天") #r("beh-siang,", "到") #r("iung-we", "之") #r("me-nyien", "末") #r("tshung-thien", "拉") #r("tau-ts", "乡下") #r("meh,", "头") #r("la", "有") #r("hyang-'au-deu", "多化") #r("yeu", "青个草") #r("too-hau", "咾") #r("tshing", "红个花") #r("kuh", "红红绿绿") #r("tshau", "实在") #r("lau,", "是") #r("'oong", "体面") #r("kuh", "得极") #r("hwo.", "个") 
#r("'Oong-'oong", "而且") #r("lok-lok", "天气") #r("zeh-zen", "也是") #r("z", "和暖") #r("(5) thi-mien", "咾")#footnote[Fine looking.] #r("tuh", "勿") #r("juh", "冷") #r("kuh,", "勿") #r("r-tshia", "热") #r("thien-chi", "所以") #r("'a", "是") #r("z", "容易") #r("(6) 'oo-noen", "使得")#footnote[Mild, warm.] #r("lau", "人人") #r("'veh", "快活") #r("lang", "咾") #r("'veh", "适意") #r("nyih,", "个") #r("soo-i", "因为") #r("z", "实在") #r("yoong-yi", "是") #r("s-tuh", "许多") #r("nyung-nyung", "人") #r("kha-weh", "宝贝") #r("lau", "第个") #r("suh-i", "春季") #r("kuh,", "个") #r("iung-we", "光阴") #r("zeh-ke", "若然") #r("lau,", "人") #r("yeu", "欢喜") #r("too-hau", "到") #r("nyung", "乡下") #r("pau-pe", "头") #r("di-kuh", "去") #r("tshung", "打猎") #r("kyi", "末") #r("kuh", "冬天") #r("kwaung-iung,", "比之") #r("zak-zen", "春天") #r("nyung", "是") #r("hwen-hyi", "更加") #r("tau", "好") #r("hyang-'au-deu", "因为") #r("chi", "冬天") #r("(1) tang-lih", "是")#footnote[To hunt.] #r("meh,", "应该") #r("toong-thien", "打猎") #r("pi-ts", "个") #r("tshung-thien", "时候") #r("z", "飞禽") #r("kung-ka", "走兽") #r("hau,", "到") #r("iung-we", "之") #r("toong-thien", "冬天") #r("z", "末") #r("iung-ke", "全") #r("tang-lih-kuh", "是") #r("z-'eu.", "长大") 
#r("(2) Fi-jung", "拉")#footnote[Birds and animals.] #r("tseu-seu", "哉。") #r("tau-ts", "旧年") #r("toong-thien", "十二月") #r("meh,", "里") #r("zen", "我") #r("z", "坐") #r("(3) tsang-doo", "之")#footnote[Full grown.] #r("la", "勃相") #r("tse.", "船") 
#r("Jeu-nyien", "同") #r("zeh-nyi", "之") #r("nyoeh", "两三个") #r("li", "知己") #r("ngoo", "朋友") #r("zoo-ts", "一淘") #r("beh-siang", "到") #r("zen,", "崑山") #r("doong-ts", "太湖") #r("liang", "咾") #r("san", "常州") #r("kuh", "咾啥") #r("ts-kyi", "个") #r("bang-yeu,", "地方") #r("ih-dau", "去") #r("tau", "打猎") #r("(4) Kwhung-san", "我伲")#footnote[Quinsan.] #r("(5) Tha-'oo", "打着")#footnote[The great lake.] #r("lau", "之") #r("(6) Dzang-tseu", "多化")#footnote[Changchow.] #r("lau-sa", "鹿") #r("kuh", "猪獾") #r("di-faung", "兔子") #r("chi", "鵓鴣") #r("tang-lih.", "野鸡") #r("Ngoo-nyi", "野鸭") #r("tang-dzak-ts", "咾啥") #r("too-hau", "等到") #r("lok,", "打好") #r("(7) ts-hoen,", "之")#footnote[Badger.] #r("thoo-ts", "猎") #r("(8) beh-koo,", "咾")#footnote[Turtle dove.] #r("ya-kyi,", "担转来") #r("ya-ah", "交代") #r("lau-sa.", "拉") #r("Tung", "大司务") #r("tau", "烧好") #r("tang", "之") #r("hau-ts", "咾") #r("lih", "吃") #r("lau,", "滋味") #r("tan-tsen", "是") #r("le", "蛮鲜") #r("kau-de", "个。") #r("la", "我伲") #r("da-s-voo", "归来") #r("sau-hau-ts", "个") #r("lau", "时候") #r("chuh,", "也") #r("(9) ts-mi", "走过")#footnote[Flavor.] #r("z", "多化") #r("man-sien", "清水河") #r("kuh.", "看见") 
#r("Ngoo-nyi", "多化") #r("kyui-le-kuh", "鱼") #r("z-'eu", "拉") #r("'a", "水里") #r("tseu", "游来游去") #r("koo", "但是") #r("too-hau", "伲") #r("(10) tshing-s-'oo,", "无没")#footnote[Stream of clear water.] #r("khoen-kyien", "网") #r("too-hau", "所以") #r("ng", "捉") #r("la", "伊拉") #r("s", "勿着。") #r("li", "总而言之") #r("yeu-le", "坐") #r("yeu-chi,", "之") #r("dan-z", "勃相") #r("nyi", "船") #r("m-meh", "咾") #r("(11) maung,", "到")#footnote[Net.] #r("soo-i", "乡下") #r("tsauh", "去") #r("yi-la", "打猎") #r("'veh-dzak.", "是") 
#r("(12) Tsoong-r", "顶好")#footnote[In short.] #r("yien-ts,", "勃相") #r("zoo-ts", "个。") #r("beh-siang", "一生一世") #r("zen", "是") #r("lau", "难班") #r("tau", "碰得着") #r("hyang-'au", "第个") #r("chi", "好") #r("tang-lih,", "机会。") #r("z", "若然") #r("ting-hau", "哪") #r("beh-siang", "勿") #r("kuh.", "相信") #r("Ih-sang", "末") #r("ih-s", "请") #r("z", "哪") #r("nan-pan", "自家") #r("bang-tuh-dzak,", "去") #r("di-kuh", "试试") #r("hau", "看") #r("kyi-we.", "难末") 
#r("Zak-zen", "晓得") #r("na", "我") #r("'veh", "个") #r("siang-sing", "说话") #r("meh,", "是") #r("tshing", "真") #r("na", "个") #r("z-ka", "也。") #r("chi", "comb") #r("s-s", "the") #r("khoen,", "hair") #r("nan-meh", "Wash") #r("hyau-tuh", "comb") #r("ngoo", "the") #r("kuh", "hair") #r("seh-wo", "Wash") #r("z", "comb") #r("tsung-kuh", "the") #r("yan.", "hair") 
