#import "../../template.typ": exercise, r

#exercise(31, "论巴急做生意积蓄铜钱", "LUNG PO-KYIH TSOO SANG-I TSIH-HYOK DOONG-DIEN")

#r("Yeu", "有") #r("ih-kuh", "一个") #r("yang-hoo", "洋货") #r("jien-khak,", "掮客，") #r("yi", "伊") #r("kuh", "个") #r("bi-chi", "脾气")#footnote[Deceived.] #r("z", "是") #r("man", "蛮") #r("oo-chi", "和气")#footnote[Accompanied.] #r("lau", "咾") #r("tsoong-'eu", "忠厚")#footnote[Pretended.] #r("le-si,", "来死，") 
#r("ih-nyien", "一年") #r("tau-deu", "到头") #r("'a", "也") #r("po-kyih", "巴急") #r("tsoo", "做") #r("kyau-yuh,", "交易")#footnote[Allow.] #r("kyau-kwan-kuh", "交关个") #r("sang-chuh", "省吃")#footnote[To put on.] #r("sang-yoong", "省用") #r("lau,", "咾，") #r("tsoo", "做") #r("nyung-ka", "人家") #r("tuh-juh,", "得极，") 
#r("kuh-lauk", "盖咾") #r("tshih-hyok-ts", "积蓄之") #r("too-hau", "多化") #r("doong-dien,", "铜钱，") #r("dzung-la", "存拉") #r("Tsung-kyung", "正金")#footnote[Yokohama Specie bank.] #r("nyung-'aung", "银行") #r("li.", "里。")

#r("'Eu-le", "后来") #r("yi", "伊") #r("tah", "搭") #r("ih-kuh", "一个") #r("ts-kyi", "知己")#footnote[Intimate.] #r("bang-yeu", "朋友") #r("keh", "合") #r("koo-vung", "股份") #r("lau", "咾") #r("khe-ts", "开之") #r("ih-ban", "一片") #r("yang-hoo-tien.", "洋货店。") 
#r("Dan-z", "但是") #r("di-kuh", "第个") #r("bang-yeu", "朋友") #r("'a", "也") #r("z", "是") #r("khung", "肯") #r("jung-jien", "勤俭")#footnote[Diligent.] #r("tsoo", "做") #r("sang-i,", "生意") #r("r-tshia", "而且") #r("'a", "也") #r("zok-sih", "熟悉")#footnote[Familiar with, skilled.] #r("yang-hoo", "洋货") #r("sang-i", "生意") #r("lau,", "咾") #r("tsu-khak", "主客") #r("zen", "全") #r("man", "蛮") #r("siang-sing", "相信") #r("yi-kuh,", "伊个，") 
#r("soo-i", "所以") #r("di-ban-tien", "第片店") #r("me-nyien", "每年") #r("dzu-theh-ts", "除脱之") #r("khe-siau", "开消") #r("meh,", "末") #r("wan", "还") #r("khau-i", "可以") #r("dzan", "赚") #r("doong-dien", "铜钱") #r("dzung-chi-le", "存起来") #r("lau,", "咾") #r("'veh-too", "勿多") #r("kyi-nyien", "几年") #r("meh,", "末，") #r("zieu", "就") #r("tuh-fah-tse.", "得发者。")#footnote[Became successful.]

#r("Nan-meh", "难末") #r("la", "拉") #r("tien", "店") #r("li", "里") #r("yeu", "有") #r("ih-kuh", "一个") #r("bau-ka", "跑街")#footnote[A drummer.] #r("sien-sang,", "先生，") #r("z", "是") #r("ih-kuh", "一个") #r("chi-liang-siau", "气量小")#footnote[Close, stingy.] #r("kuh-nyung,", "个人，") 
#r("khoen-kyien", "看见") #r("yi-la", "伊拉") #r("tuh-fah-ts", "得发之") #r("meh,", "末，") #r("ngan-nyih-tse,", "眼热者，")#footnote[Very desirous (Hot eyes).] #r("iau-siang", "要想") #r("tsoo", "做") #r("choen-thau", "圈套")#footnote[Snare.] #r("peh", "拨") #r("yi-la", "伊拉") #r("ta", "戴") #r("lau,", "咾") #r("phien", "骗") #r("yi-la", "伊拉") #r("doong-dien.", "铜钱。") 
#r("'Eu-le", "后来") #r("yi", "伊") #r("tah", "搭") #r("ih-kuh", "一个") #r("fan-hyi", "翻戏") #r("tshen-thoong-ts", "串通之")#footnote[Conspired with a sharper.] #r("lau,", "咾") #r("iau-siang", "要想") #r("peh-yi", "拨伊") #r("liang-kuh", "两个") #r("toong-ka", "东家") #r("zaung-taung,", "上当。") #r("soo-i", "所以") #r("yi", "伊") #r("be-ts", "倍之") #r("ih-kuh", "一个") #r("fan-hyi", "翻戏") #r("tau", "到") #r("tien-li", "店里") #r("chi", "去") #r("lau", "咾") #r("the-thauh", "推託") #r("z", "是") #r("ih-kuh", "一个") #r("doo", "大") #r("tsu-khak", "主客") #r("lau", "咾") #r("nyang", "让") #r("liang-kuh", "两个") #r("lau-ban", "老班") #r("tah", "搭") #r("yi", "伊") #r("tsoo", "做") #r("bang-yeu.", "朋友。")

#r("Nan-meh", "难末") #r("di-kuh", "第个") #r("fan-hyi", "翻戴") #r("tsaung-tsheh", "装出") #r("z", "是") #r("yeu", "有") #r("doong-dien", "铜钱") #r("lau,", "咾，") #r("nyih-nyih", "日日") #r("tshing", "请") #r("liang-kuh", "两个") #r("lau-ban", "老班") #r("chuh", "吃") #r("da-tshe", "大菜")#footnote[Big dinners.] #r("'ok-tse", "或者") #r("chuh", "吃") #r("hwo-tsieu", "花酒")#footnote[Wine.] #r("lau-sa.", "咾啥。") 
#r("Yi-la", "伊拉") #r("gah-ts", "轧之") #r("zeh-kyi-nyih", "十几日") #r("dau-ben", "淘伴") #r("meh,", "末") #r("iau", "要") #r("siang", "想") #r("keh", "合") #r("yi-la", "伊拉") #r("tsoo", "做") #r("sang-i,", "生意，") #r("'ok-tse", "或者") #r("too-doong-dien", "赌铜钱") #r("tse.", "者。") 
#r("Nan-meh", "难末") #r("chui-tuh", "亏得") #r("yeu", "有") #r("ih-kuh", "一个") #r("kyien-suh", "见识") #r("hau-kuh-nyung", "好个人")#footnote[A good man of understanding.] #r("la", "拉") #r("pien-deu", "旁边头") #r("khoen-tsheh", "看出") #r("z", "是") #r("ih-kuh", "一个") #r("fan-hyi,", "翻戏，") 
#r("soo-i", "所以") #r("lih-khuh", "立刻") #r("kwan-tsau", "关照")#footnote[To inform.] #r("di-kuh", "第个") #r("liang-kuh", "两个") #r("yang-hoo-tien", "洋货店") #r("lau-ban.", "老班。") 
#r("Nan-meh", "难末") #r("yi-la", "伊拉") #r("lien-maung", "连忙") #r("'veh-gah-tau", "勿轧淘") #r("lau", "咾") #r("li-khe.", "离开。") 
#r("Soe-zen", "虽然") #r("di-kuh", "第个") #r("fan-hyi", "翻戏") #r("dzung-jeu", "仍旧") #r("sia", "寫") #r("tshing-khak-phiau,", "请客票") #r("chi", "去") #r("yung-yeu", "引诱") #r("yi-la", "伊拉") #r("le", "来") #r("chuh-jok", "吃局") #r("meh,", "末，") 
#r("di-kuh", "第个") #r("liang-kuh", "两个") #r("lau-ban", "老班") #r("tsoong", "终") #r("'veh", "勿") #r("chi,", "去，") #r("lien-laung", "连上") #r("ng-lok", "五六") #r("we", "回") #r("chi", "去") #r("tshing", "请") #r("'veh-tau-meh", "勿到末，") 
#r("di-kuh", "第个") #r("bau-ka", "跑街") #r("sien-sang,", "先生，") #r("tah", "搭") #r("fan-hyi", "翻戏") #r("hyau-tuh,", "晓得") #r("yi-la", "伊拉") #r("kauh-dzak", "觉着") #r("tse,", "者，") 
#r("nan-meh", "难末") #r("than-chi", "嘆气")#footnote[Sigh.] #r("lau", "咾") #r("wo,", "话，") #r("di-kuh", "第个") #r("tsung-tsung", "真真") #r("kyau,", "叫") #r("theu", "偷") #r("kyi", "鸡") #r("'veh-dzak", "勿着") #r("zeh", "蚀") #r("po", "把") #r("mi", "米") #r("yan.", "也。")#footnote[Did not steal the chicken and lost a handful of rice.]
