#import "../../template.typ": exercise, r

#exercise(54, "论大概人欢喜那能个日脚", "LUNG DA-KE NYUNG HWEN-HYI NA-NUNG KUH NYIH-KYAK")

#r("Zauh-ya-deu", "昨夜头") #r("ngoo", "我") #r("we-ts", "为之") #r("sung-thi", "身体")  #r("bi-joen", "疲倦")#footnote[Weary.] #r("lau", "咾") #r("iau-siang", "要想") #r("tsau-tien", "早点") #r("chi", "去") #r("kwhung,", "睏，") #r("zieu", "就") #r("tien-ts", "点之") #r("lah-tsok", "蜡烛") #r("hoo,", "火")  #r("zaung-leu,", "上楼，")#footnote[To go up stairs.] #r("tsing-ts", "进之") #r("vaung-kan,", "房间")  #r("thoeh-ts", "脱之")#footnote[To take off.] #r("'a-ts", "鞋子") #r("lau", "咾") #r("i-zaung,", "衣裳") #r("tsak-ts", "着之") #r("kwhung-i,", "睏衣")  #r("hyau-khe-ts", "揭开之")#footnote[Turn back or open.] #r("zaung-laung", "牀上") #r("kuh", "个") #r("bi,", "被")  #r("tsh-iung-ts", "吹隐之")#footnote[To blow out.] #r("hoo", "火") #r("lau", "咾") #r("kwhung-tse.", "睏哉。") 

#r("Dan-z,", "但是") #r("we-ts", "为之") #r("koo-vung", "过分") #r("bi-joen", "疲倦") #r("lau", "咾") #r("tau", "倒") #r("'veh-nung", "勿能") #r("zieu", "就") #r("kwhung-dzak,", "睏着") #r("dzuh-tau", "直到") #r("zeh-tien-tsoong-kuh", "十点钟个") #r("z-'eu,", "时候") #r("khan-khan", "纔纔") #r("kwhung-dzak,", "睏着。") #r("soe-zen", "虽然") #r("z-kwhung-dzak,", "是睏着") #r("zen-r", "然而") #r("sung-thi", "身体") #r("dzang-tsaung", "常庄")  #r("fan-tsen.", "翻转。")#footnote[To roll back and forth.] #r("fan-tsen", "翻转") #r("tau-ts", "到之") #r("pen-ya", "半夜") #r("zieu", "就")  #r("kau-sing-tse.", "觉醒哉。")#footnote[To awake.] #r("thing-kyien", "听见") #r("nga-mien", "外面") #r("la", "拉") #r("hyui-lau.", "雨落。") #r("nan-meh", "难末") #r("siang", "想") #r("tse-kwhung", "再睏") #r("ih-hyih.", "一歇。") #r("Kwhung-ts", "睏之") #r("ih-hyih", "一歇") #r("thien", "天") #r("zieu", "就") #r("liang-tse.", "亮哉。") 

#r("Dan-z", "但是") #r("yien-dze", "现在")  #r("nyih-kwaung", "日光")#footnote[The light of day a little shorter.] #r("sau-we", "稍为") #r("toen-tien-tse.", "短点哉。") #r("lauh-yui", "落雨") #r("kuh", "个") #r("nyih-kyak,", "日脚，") #r("kung-ka", "更加") #r("kauh-dzak", "觉着")  #r("nyih", "日") #r("toen", "短") #r("ya", "夜") #r("dzang.", "长。")#footnote[Short days, long nights.] #r("Tsau-zung", "早晨") #r("lok", "六") #r("tien-tsoong,", "点钟") #r("thien", "天") #r("wan-'veh-zung", "还勿曾") #r("liang,", "亮。") #r("zen-r", "然而") #r("yeu-kuh", "有个") #r("nyung", "人") #r("iung-we", "因为") #r("lan-doo,", "懒惰") #r("lau", "咾") #r("hyi-hwen", "喜欢") #r("ya", "夜") #r("dzang", "长") #r("nyih", "日") #r("toen.", "短。") #r("'A", "也") #r("yeu", "有") #r("kuh", "个") #r("nyung", "人") #r("hyi-hwen", "喜欢") #r("ya", "夜") #r("dzang", "长") #r("nyih", "日") #r("toen", "短") #r("meh,", "末") #r("iung-we", "因为") #r("yi", "伊") #r("e", "爱") #r("ya-li", "夜里")  #r("tshing-dzing", "清静")#footnote[Quiet, still.] #r("lau,", "咾") #r("khau-i", "可以") #r("too", "多") #r("dok-su", "读书") #r("yan.", "也。") 

#r("Zen-r", "然而") #r("wan", "还") #r("yeu", "有") #r("kuh", "个") #r("nyung", "人") #r("hyi-hwen", "喜欢") #r("ya", "夜") #r("dzang", "长") #r("nyih", "日") #r("toen", "短") #r("meh,", "末") #r("iung-we", "因为") #r("yi", "伊") #r("z", "是") #r("e", "爱") #r("too", "多") #r("khoen", "看") #r("ya", "夜") #r("hyi", "戏") #r("lau", "咾")  #r("'an-yeu", "闲游") #r("laung-daung.", "浪荡。")#footnote[To go idly about.] #r("Ye", "也") #r("e", "爱") #r("tsien", "全") #r("ya", "夜") #r("too", "赌") #r("doong-dien.", "铜钱。") #r("R-tshia", "而且") #r("yeu", "有") #r("nyung", "人") #r("tau", "倒") #r("hyi-hwen", "喜欢") #r("yui-lauh", "落雨") #r("thien.", "天。") #r("iung-we", "因为") #r("yui-lauh", "雨落") #r("thien", "天") #r("meh", "末") #r("khau-i", "可以") #r("too", "多") #r("tung", "登") #r("la", "拉") #r("ok-li", "屋里") #r("lau", "咾") #r("'veh-iau", "勿要") #r("tsheh-chi", "出去") #r("tsoo", "做") #r("z-thi", "事体") #r("tse.", "哉。") 

#r("Ngoo", "我") #r("yeu", "有") #r("ih-kuh", "一个") #r("bang-yeu", "朋友") #r("z", "是") #r("tsoo", "做")  #r("tshau", "操") #r("ping", "兵") #r("kuh", "个") #r("kuh", " ") #r("kyau-yoen.", "教员。")#footnote[Drill instructor.] #r("Yi", "伊")  #r("dzung-kyung", "曾经")#footnote[Already.] #r("te", "对") #r("ngoo", "我") #r("wo,", "话，") #r("ngoo", "我") #r("z", "是") #r("tsoe", "最") #r("hyi-hwen", "喜欢") #r("yui-lauh", "雨落") #r("thien,", "天，") #r("iung-we", "因为") #r("yui-lauh", "雨落") #r("thien", "天") #r("meh", "末") #r("khau-i", "可以") #r("'veh", "勿") #r("tsheh-chi", "出去") #r("kyau", "教") #r("tshau.", "操。") #r("Yien-dze", "现在") #r("ngoo", "我") #r("tshing-mung", "请问") #r("na", "哪") #r("kauh-we,", "各位，") #r("z", "是") #r("hyi-hwen", "喜欢") #r("ya", "夜") #r("dzang", "长") #r("nyi", "呢") #r("ya", "夜") #r("toen", "短") #r("thien", "天") #r("hau", "好") #r("nyi", "呢") #r("yui-lauh.", "雨落。") #r("Tshing", "请") #r("na", "哪") #r("kau-soo", "告诉") #r("ngoo.", "我。")
