#import "../../template.typ": exercise, r

#exercise(61, "论青年会聚集一个禁烟大会", "LUNG TSHING-NYIEN-WE DZUI-DZIH IH-KUH KYUNG-IEN DA WE")

#r("Zauh-nyih", "昨日") #r("'au-pen-nyih", "下半日") #r("s", "四") #r("tien-tsoong,", "点钟，") #r("la", "拉") #r("Tsoong-kok", "中国") #r("Tshing-nyien-we", "青年会")#footnote[Y. M. C. A.] #r("dzui", "聚集") #r("kyung-ien", "禁烟")#footnote[Prohibit opium.] #r("da-we,", "大会，") #r("dzui", "聚") #r("we", "会") #r("kuh", "个") #r("nyung", "人") #r("z", "是") #r("'veh-sau.", "勿少。") 

#r("Sien", "先") #r("z", "是") #r("tshing", "请") #r("Tshing-nyien-we", "青年会") #r("li", "里") #r("kuh", "个") #r("we-tsung", "会正") #r("yien-seh.", "演説")#footnote[The president spoke.] #r("Yi", "伊") #r("wo,", "话，") #r("Tsoong-kok", "中国") #r("tshing-nyien-kuh", "青年个") #r("nyung", "人") #r("iung-ke", "应该") #r("dzing-lih", "尽力")#footnote[Utmost strength.] #r("chi-theh", "弃脱") #r("a-phien-ien", "鸦片烟")#footnote[Opium.] #r("kuh", "个") #r("'e-tshu,", "害处，") #r("dzing", "尽") #r("ngoo-nyi", "我伲") #r("kyeu", "救") #r("kok", "国") #r("kuh", "个") #r("ming-vung.", "名分。")#footnote[Duty.] 

#r("Zak-zen", "若然") #r("ngoo-nyi", "我伲") #r("'veh", "勿") #r("choen", "劝") #r("bih", "别") #r("nyung", "人") #r("ka", "戒") #r("ien", "烟")#footnote[Break off opium.] #r("'veh-dan", "勿但") #r("seh-theh-ts", "失脱之") #r("van-kok", "万国") #r("kyung-ien", "禁烟") #r("kuh", "个") #r("hau", "好") #r("i,", "意，") #r("r-tshia", "而且") #r("seh-theh", "失脱") #r("Tsoong-kok", "中国") #r("nyung", "人") #r("kuh", "个") #r("thi-mien.", "体面。")#footnote[Respectability ] #r("Ngoo", "我") #r("iau", "要") #r("tshing", "请") #r("Tshing-nyien-we", "青年会") #r("tsu-kyuin", "诸君")#footnote[Gentlemen.] #r("paung-dzoo", "帮助") #r("di-kuh", "第个") #r("z-thi.", "事体。") 

#r("Yi", "伊") #r("wo-we-ts,", "话完之，") #r("nan-meh", "难末") #r("yeu", "有") #r("ih-we", "一位") #r("Tsoong-kok", "中国") #r("kyung-ien-we-kuh", "禁烟位个") #r("de-piau", "代表")#footnote[Representative.] #r("lih-chi-le", "立起来") #r("wo,", "话") #r("ngoo-nyi", "我伲") #r("Tsung-foo", "政府")#footnote[Government.] #r("iau", "要") #r("dzing-lih,", "尽力，") #r("kyung-ts", "禁止") #r("a-phien-ien", "鸦片烟")#footnote[Prohibit.] #r("lau,", "咾，") #r("r-tshia", "而且") #r("tuh-dzak", "得着") #r("kauk-kok", "各国") #r("siang-paung", "相帮") #r("nyi.", "伲。") #r("Di-kuh", "第个") #r("z", "是") #r("ting", "顶") #r("hau-kuh", "好个") #r("kyi-we,", "机会，") #r("tsoong", "终") #r("'veh", "勿") #r("khau-i", "可以") #r("seh-theh", "失脱") #r("kuh.", "个。") 

#r("A-phien-ien-kuh", "鸦片烟个") #r("dok,", "毒，") #r("da-ke", "大概") #r("nyung", "人") #r("zen", "全") #r("hyau-tuh,", "晓得，") #r("tsho-'veh-too", "差勿多") #r("phoo", "鋪") #r("me", "满")#footnote[Fills.] #r("la", "拉") #r("Tsoong-kok", "中国") #r("zeh-pah", "十八") #r("sang;", "省") #r("soo-i", "所以") #r("kok-doo", "国度") #r("zeh-ke", "实盖") #r("joong", "穷")#footnote[Poor.] #r("lau", "咾") #r("zak.", "弱。") 

#r("Zak-z", "若是") #r("Tsoong-kok", "中国") #r("nyung-tsung", "认真") #r("dzu-theh", "除脱") #r("di-kuh", "第个") #r("'e", "害") #r("meh,", "末，") #r("'eu-le", "后来") #r("khau-i", "可以") #r("la", "拉") #r("s-ka", "世界") #r("laung", "上") #r("tsoo", "做") #r("ih-kuh", "一个") #r("jang", "强") #r("kok.", "国。")#footnote[Strong nation.] #r("Tsoong", "衆") #r("nyung", "人") #r("thing-kyien-ts", "听见之") #r("yi", "伊") #r("kuh", "个") #r("seh-wo,", "説话，") #r("zen", "全") #r("ke-doong", "感动") #r("tuh-juh", "得极") #r("lau,", "咾，") #r("phak", "拍") #r("seu", "手") #r("'veh", "勿") #r("ding.", "停。") #r("Tung-tau", "等到") #r("san", "散") #r("we", "会") #r("kuh", "个") #r("z-'eu,", "时候，") #r("i-kyung", "已经") #r("lok", "六") #r("tien-tsoong", "点钟") #r("tse.", "哉。")
