#import "../../template.typ": exercise, r

#exercise(53, "论一张告示", "LUNG IH-TSANG-KAU-Z")

#r("Zauh-nyih", "昨日") #r("'au-pen-nyih,", "下半日") #r("ngoo", "我") #r("tah-ts", "搭之") #r("kyi-kuh", "几个") #r("bang-yeu", "朋友") #r("ih-dau", "一淘") #r("tau", "到") #r("dzung", "城") #r("li", "里") #r("chi", "去") #r("beh-siang.", "勃相。") 
#r("Nyi", "伲") #r("tseu", "走") #r("tau", "到") #r("tau", " ") #r("Sing-pok-mung", "新北门") #r("kheu-deu,", "口头") #r("khoen-kyien", "看见")  #r("ih-juin", "一羣") #r("nyung", "人") #r("la", "拉")  #r("ngauh-chi-ts", "昂起之") #r("deu", "头") #r("lau", "咾") #r("te", "对") #r("ziang-deu", "墙头") #r("khoen-la.", "看拉。") 
#r("Ngoo", "我") #r("siang", "想") #r("yi-la,", "伊拉") #r("la", "拉") #r("khoen", "看") #r("hyi-kwen-li", "戏馆里") #r("kuh", "个")  #r("hyi-tan.", "戏单。") 
#r("Dan-z", "但是") #r("ngoo", "我") #r("tseu-koo", "走过") #r("chi", "去") #r("ih-khoen", "一看") #r("bing", "并") #r("'veh-z", "勿是") #r("hyi-tan,", "戏单，") #r("z", "是") #r("ih-tsang", "一张") #r("sing-tseh", "新出") #r("la-kuh", "拉个") #r("kau-z.", "告示。") 
 #r("Tsiang-oo", "浆糊") #r("wan", "还") #r("'veh-zung", "勿曾") #r("koen,", "乾，") #r("soo-i", "所以") #r("yeu", "有") #r("kyi-kuh", "几个") #r("z", "字") #r("khoen-da-'veh-tsheh.", "看大勿出。") 
#r("Di-tsang", "第张") #r("kau-z", "告示") #r("z", "是")  #r("Zaung-he", "上海") #r("yoen-li", "县里") #r("fah-tsheh-le-kuh.", "发出来个。") 
#r("Yien-dze", "现在") #r("ngoo", "我") #r("iau", "要") #r("pe", "背") #r("peh", "拨") #r("na", "哪") #r("thing", "听") #r("kau-z", "告示") #r("laung", "上") #r("kuh", "个") #r("seh-wo.", "说话。") 
#r("S-kyi", "四季") #r("taung-tsoong,", "当中") #r("'au", "夏") #r("lau", "咾") #r("tshieu", "秋") #r("liang-kyi,", "两季") #r("z", "是") #r("ting", "顶") #r("nyih.", "热。") 
#r("Yien-dze", "现在") #r("na", "哪") #r("hyau-tuh", "晓得") #r("z", "是") #r("'au", "夏") #r("kyi", "季") #r("kuh", "个") #r("chi-deu.", "起头。") 
#r("Thien-chi", "天气") #r("meh,", "末")  #r("dzien-dzien-nung", "渐渐能") #r("nyih-chi-le", "热起来") #r("tse.", "哉。") 
#r("La", "拉") #r("thien-chi", "天气") #r("nyih-kuh", "热个") #r("z-'eu", "时候") #r("nyung", "人") #r("yoong-i", "容易") #r("sang", "生") #r("bing", "病") #r("lau", "咾") #r("kauh-yang", "各样") #r("meh-z", "物事") #r("yoong-i", "容易")  #r("fah-me,", "发霉。")#footnote[To mould.] 
#r("soo-i", "所以") #r("yien-dze", "现在") #r("ngoo", "我") #r("(yoen-kwen)", "县官") #r("iau", "要") #r("kau-soo", "告诉") #r("na", "哪") #r("kyi-yang", "几样") #r("fah-ts,", "法子") #r("s", "使") #r("na", "哪") #r("khau-i", "可以") #r("mien-theh", "免脱") #r("too-hau", "多化")  #r("ngwe-hyien", "危险")#footnote[Dangerous.] #r("kuh", "个") #r("mau-bing,", "毛病。") #r("zieu-z", "就是：")  #r("fah-so,", "发痧、")#footnote[A form of cholera.] #r("hauh-loen", "霍乱、") #r("thoo-sia,", "吐泻") #r("lau-sa.", "咾啥。") 

#r("deu", "头") #r("ih", "一") #r("meh", "末") #r("na", "哪") #r("dzu-kuh", "住个") #r("vaung-ts", "房子") #r("iau", "要") #r("koen-zing,", "干净。") #r("di-pan", "地板") #r("meh,", "末") #r("dzang-tsaung", "常庄") #r("iau", "要")  #r("thoo;", "拖。")#footnote[To mop.] 
#r("thien-tsing", "天井") #r("meh,", "末") #r("dzang-tsaung", "常庄") #r("iau", "要") #r("da;", "汏。") 
 #r("ding-sing", "庭心")#footnote[Court yard.] #r("li", "里") #r("kuh", "个")  #r("iung-keu", "阴沟")#footnote[Drain.] #r("meh,", "末") #r("dzang-z", "常时") #r("iau", "要")  #r("yoong", "用") #r("s-le", "水来") #r("tshoong,", "冲，")#footnote[To flush.] #r("'veh-iau", "勿要") #r("peh", "拨") #r("yi", "伊")  #r("suh-meh.", "塞没。")#footnote[Clogged.] 
#r("Zak-zen", "若然") #r("iung-keu", "阴沟") #r("'veh-tshoong,", "勿冲，") #r("keh-meh", "盖末") #r("auh-tsauh", "龌龊") #r("z", "是") #r("'veh-we", "勿会") #r("lieu-tsheh-chi,", "流出去。") #r("nan-meh", "难末") #r("iau", "要") #r("sang-tsheh", "生出") #r("tsheu-chi", "臭气") #r("le,", "来。") 
#r("nyung", "人")  #r("mung-dzak-ts", "闻着之")#footnote[To smell.] #r("meh,", "末") #r("iau", "要") #r("fah-so-kuh.", "发痧个。") 
#r("Nyung-ka", "人家") #r("iung-ke", "应该") #r("yui-be", "预备") #r("ih-kung", "一根")  #r("thoong-diau,", "通条，")#footnote[A probing rod.] #r("thien-tsing", "天井") #r("li", "里") #r("kuh", "个") #r("iung-keu", "阴沟") #r("suh-meh", "塞没") #r("meh,", "末") #r("zieu", "就") #r("yoong", "用") #r("thoong-diau", "通条") #r("le", "来") #r("thoong.", "通。") 

#r("Di-nyi,", "第二") #r("z", "是") #r("kaung-tau", "讲到") #r("chuh-kuh", "吃个") #r("meh-z.", "物事。") 
#r("Na", "哪") #r("chuh", "吃") #r("meh-z,", "物事") #r("deu-ih", "头一") #r("iau-kyung", "要紧") #r("iau", "要")  #r("chien-yuin,", "牵匀，")#footnote[Well adjusted, regular diet.] #r("chuh-kuh", "吃个") #r("siau-tshe", "小菜") #r("ih-ding", "一定") #r("iau", "要")  #r("sing-sien", "新鲜")#footnote[Fresh.] #r("lau", "咾")  #r("sau-tuh", "烧得") #r("zok,", "熟。")#footnote[To cook thoroughly.] 
 #r("kak-ya-kuh", "隔夜个")#footnote[Food kept over night.] #r("siau-tshe", "小菜") #r("meh,", "末") #r("tsoong", "终") #r("'veh-iau", "勿要") #r("chuh;", "吃；") #r("kauh-yang", "各样") #r("sang-kuh", "生个") #r("s-koo", "水果") #r("lau", "咾") #r("'veh", "勿") #r("yoong-i", "容易")  #r("siau-hwo", "消化")#footnote[Digest.] #r("kuh", "个") #r("meh-z", "物事") #r("'a", "也") #r("'veh", "勿") #r("iung-ke", "应该") #r("chuh-kuh;", "吃个；") 
#r("la", "拉") #r("ka-laung", "街上") #r("ma-kuh", "卖个") #r("si-kwo", "西瓜")  #r("mih-doong", "密同") #r("kwo,", "瓜、")#footnote[A kind of melon.]  #r("'oo-lan-s,", "嘴囔水、")#footnote[Aerated waters.]  #r("liang-fung,", "凉粉、")#footnote[Iced drinks.]  #r("ping-kyi-ling", "冰唭呤")#footnote[Ice-cream.] #r("lau-sa,", "咾啥，") #r("tsoong", "终") #r("'veh-iau", "勿要") #r("chuh.", "吃。") 
#r("Chuh-ts", "吃之") #r("meh,", "末") #r("iau", "要") #r("doo-li", "肚里") #r("sia", "泻") #r("lau", "咾") #r("dzung-koong", "成功") #r("hauh-loen", "霍乱") #r("thoo-sia.", "吐泻。") 
#r("Na", "哪") #r("chuh-kuh", "吃个") #r("meh-z", "物事") #r("tsoong-iau", "终要") #r("khaung-la", "园拉") #r("ping-siang", "冰箱") #r("li,", "里，") #r("'ok-tse", "或者") #r("yoong", "用") #r("ih-tsak", "一只")  #r("so-tsau", "纱罩")#footnote[A screen cover.] #r("le", "来") #r("tsau-hau,", "罩好，") #r("'veh", "勿") #r("iau", "要") #r("peh", "拨")  #r("tshaung-iung", "苍蝇")#footnote[Flies.] #r("lau", "咾")  #r("mo-nyi", "蚂蚁")#footnote[Ants.] #r("tsing-chi.", "进去。") 

#r("Di", "第") #r("san.", "三。") #r("Na", "哪") #r("iung-ke", "应该") #r("dzang-tsaung", "常庄") #r("zing-yok,", "净浴，") #r("dan-z", "但是") #r("'veh-iau", "勿要") #r("tau", "到") #r("pang-li", "浜里") #r("chi", "去") #r("zing", "净")  #r("lang-s-yok,", "冷水浴，")#footnote[Cold water bath.] 
#r("iung-we", "因为") #r("la", "拉") #r("nyih-thien,", "热天") #r("pang", "浜") #r("li", "里") #r("yeu", "有") #r("dok-chi,", "毒气，") #r("ping-tshia", "并且") #r("yeu", "有") #r("dzang-z", "常时") #r("'veh", "勿") #r("taung-sing", "当心") #r("meh,", "末") #r("iau", "要")  #r("dzung-sah.", "沉杀。")#footnote[Drowned.] 
#r("Na", "哪") #r("'a", "也") #r("'veh", "勿") #r("iung-ke", "应该")  #r("tshak-ts-pok", "赤之膊")#footnote[Naked.] #r("tau", "到")  #r("tha-yang", "太阳")#footnote[The sun.] #r("li", "里") #r("chi", "去") #r("bau-le", "跑来") #r("bau-chi,", "跑去，") 
#r("iung-we", "因为") #r("nyih-chi", "热气") #r("tau-ts", "到之") #r("sung-thi", "身体") #r("li", "里") #r("chi", "去") #r("meh,", "末") #r("iau", "要")  #r("sang-nyih-tsih-deu", "生热疖头")#footnote[Sun stroke.] #r("lau,", "咾") #r("'a", "也") #r("iau", "要") #r("fah-so.", "发痧。") 
#r("Ya", "夜") #r("li", "里") #r("na", "哪") #r("'veh", "勿") #r("iau", "要") #r("kwhung-la", "睏拉")  #r("loo-thien,", "露天，")#footnote[In the open air, out of doors.] #r("iung-we", "因为") #r("yeu", "有") #r("lang-loo-s", "冷露水") #r("lauh-la", "落拉") #r("na-kuh", "哪个") #r("sung-laung", "身上") #r("meh,", "末") #r("iau", "要") #r("sang-bing-kuh.", "生病个。") 

#r("Di", "第") #r("s.", "四。") #r("Na", "哪") #r("iung-ke", "应该") #r("taung-sing", "当心") #r("na-kuh", "哪个") #r("i-zaung.", "衣裳。") #r("Na", "哪") #r("la", "拉") #r("nyih-thien", "热天") #r("doo", "多") #r("tseu-ts-loo,", "走之路") #r("'ok-tse", "或者") #r("too", "多") #r("tsoo-ts", "做之") #r("sang-weh,", "生活，") #r("sung-thi", "身体") #r("iau", "要")  #r("tsheh-oen;", "出汗；")#footnote[Perspire.] 
#r("na", "哪") #r("tsak-la-kuh", "穿着拉个") #r("i-zaung", "衣裳") #r("'a", "也") #r("yeu", "有") #r("oen", "汗") #r("la-laung.", "拉上。") 
 #r("Peh", "拨") #r("oen-tsheh-sak-kuh", "汗湿个")#footnote[Wet by perspiration.] #r("i-zaung", "衣裳") #r("iung-ke", "应该") #r("zing-koo-ts", "净过之") #r("lau", "咾") #r("tse-tsak;", "再着；") #r("'veh-iau", "勿要") #r("tung", "等") #r("de", "待") #r("oen", "汗") #r("koen-ts", "乾之") #r("lau", "咾") #r("tse-tsak", "再着") #r("la", "拉") #r("sung-laung.", "身上。") 
#r("Na", "哪") #r("khaung-la", "园拉") #r("siang-ts", "箱子") #r("li", "里") #r("kuh", "个") #r("i-zaung", "衣裳") #r("iung-ke", "应该") #r("dzang-tsaung", "常庄") #r("tan-tsheh-le", "担出来")  #r("so-so,", "晒晒")#footnote[To sun.] #r("'veh-iau", "勿要") #r("peh", "拨") #r("yi", "伊") #r("me-theh.", "霉脱。") 
#r("Zak-zen", "若然") #r("na", "哪") #r("tsak-ts", "着之") #r("yeu", "有") #r("me-kuh", "霉个") #r("i-zaung,", "衣裳，") #r("me-chi", "霉气") #r("iau", "要") #r("tau", "到") #r("sung-thi", "身体") #r("li", "里") #r("chi", "去") #r("lau", "咾") #r("s-tuh", "使得") #r("na", "哪") #r("sang-bing-kuh.", "生病个。") 

#r("Ngoo", "我") #r("(yoen-kwen)", "县官") #r("maung", "望") #r("na", "哪") #r("tsau", "照") #r("ngoo-kuh", "我个") #r("fah-tsuh", "法则")  #r("pau-'oo", "保护")#footnote[Protect.] #r("na-kuh", "哪个") #r("sung-thi,", "身体，") #r("mien-theh", "免脱") #r("too-hau", "多化") #r("we-hyien", "危险") #r("kuh", "个") #r("mau-bing.", "毛病。") 
#r("Na", "哪") #r("kuh", "个") #r("bang-yeu", "朋友") #r("lau", "咾") #r("tshing-kyoen", "亲眷") #r("lau", "咾")  #r("ling-so,", "邻舍")#footnote[Neighbor.] #r("zak-zen", "若然") #r("yi-la", "伊拉") #r("'veh-zung", "勿曾") #r("khoen-kyien", "看见") #r("di-tsang", "第张") #r("kau-z,", "告示，") #r("na", "哪") #r("iung-ke", "应该") #r("kau-soo", "告诉") #r("yi-la.", "伊拉。") 
#r("Di-kuh", "第个") #r("z", "是") #r("na-kuh", "哪个")  #r("ming-vung", "名分")#footnote[One's duty.] #r("yan.", "也。")
