#import "../../template.typ": exercise, r

#exercise(67, "论识字个好处", "LUNG SUH-Z-KUH HAU-TSHU")

#r("Ngoo", "我") #r("la", "拉") #r("ih", "一") #r("pang", "本") #r("su", "书") #r("laung", "上") #r("khoen-kyien", "看见") #r("ih-tsaung", "一桩") #r("koo-tien,", "古典，") #r("z", "是") #r("lung-tau", "论到") #r("liang-kuh", "两个") #r("nyung,", "人，") #r("ih-kuh", "一个") #r("meh,", "末") #r("suh-z-kuh", "识字个") #r("lau,", "咾") #r("(4)", " ") #r("bi-theh-we-hyien,", "避脱危险")#footnote[Avoid danger.] #r("ih-kuh", "一个") #r("meh,", "末") #r("'veh", "勿") #r("suh", "识") #r("z-kuh", "字个") #r("lau,", "咾") #r("seh-theh", "失脱") #r("sing-ming.", "性命。") 

#r("La", "拉") #r("(5)", " ") #r("meu-tshu", "某处")#footnote[A certain place.] #r("di-faung", "地方") #r("yeu", "有") #r("ih-zoo", "一座") #r("san,", "山。") #r("di-zoo", "第座") #r("san", "山") #r("laung", "上") #r("'veh-dan", "勿但") #r("kyung-ts", "景致") #r("hau,", "好") #r("r-tshia", "而且") #r("yeu", "有") #r("too-hau", "多化") #r("(6)", " ") #r("koo-tsih,", "古蹟。")#footnote[Ancient ruins.] #r("soo-i", "所以") #r("dzang-tsaung", "常庄") #r("yeu", "有") #r("nyung", "人") #r("chi", "去") #r("beh-siang", "勃相") #r("lau,", "咾") #r("'a", "也") #r("yeu", "有") #r("too-hau", "多化") #r("ngen-bung-kuh", "呆笨个") #r("nyung", "人") #r("tau", "到") #r("san", "山") #r("laung-kuh", "上个") #r("miau-li", "庙里") #r("chi", "去") #r("sau-hyang.", "烧香。") #r("Keh-lau", "盖咾") #r("di-zoo", "第座") #r("san", "山") #r("laung-kuh", "上个") #r("tien-ka", "店家") #r("meh,", "末") #r("kung-ka", "更加") #r("too", "多") #r("lau", "咾") #r("nau-mang", "闹猛") #r("tuh-juh.", "得极。") 

#r("'Eu-le", "后来") #r("i", "伊") #r("zoo", "座") #r("san-laung", "山上") #r("hweh-zen", "忽然") #r("yeu", "有") #r("kyi", "几") #r("tsak", "只") #r("lau-hoo,", "老虎。") #r("dzang-tsaung", "常庄") #r("tsheh-le", "出来") #r("chuh-nyung,", "吃人") #r("i-ts", "以致") #r("m", "无") #r("nyung", "个人") #r("zaung", "上") #r("chi", "去") #r("beh-siang", "勃相") #r("tse.", "哉。") 

#r("San-laung", "山上") #r("khe", "开") #r("tien-kuh-nyung", "店个人") #r("da-ka", "大家") #r("saung-liang,", "商量") #r("tshing", "请") #r("kyi", "几") #r("kuh", "个") #r("(7)", " ") #r("tang-lih-kuh-nyung", "打猎个人")#footnote[A hunter.] #r("le", "来") #r("tang-sah", "打杀") #r("lau-hoo,", "老虎") #r("dzu-theh", "除脱") #r("di-faung", "地方") #r("laung-kuh", "上个") #r("'e-tshu,", "害处") #r("'a", "也") #r("z", "是") #r("ih-tsaung", "一桩") #r("hau", "好") #r("z-thi.", "事体。") #r("Yi-la", "伊拉") #r("saung-liang", "商量") #r("ding-taung-ts", "定当之") #r("meh,", "末") #r("zieu", "就") #r("tshing-ts", "请之") #r("kyi-kuh", "几个") #r("tang-lih-kuh-nyung.", "打猎个人。") 

#r("Tang-lih-kuh-nyung", "打猎个人") #r("'veh", "勿") #r("tan", "担") #r("yang-tshiang", "洋鎗") #r("le", "来") #r("tang", "打") #r("lau-hoo,", "老虎") #r("dan-z", "但是") #r("yi-la", "伊拉") #r("la", "拉") #r("di", "地") #r("laung", "上") #r("joeh-ts", "掘之") #r("kyi-kuh", "几个") #r("di-doong,", "地洞") #r("li-mien", "里面") #r("tsang", "张") #r("ih-tsang", "一张") #r("(1)", " ") #r("koong", "弓")#footnote[A bow.] #r("lau", "咾") #r("(2)", " ") #r("ih-ts-tsien.", "一枝箭。")#footnote[An arrow.] #r("Lau-hoo", "老虎") #r("tseu-tau", "走到") #r("i-deu", "伊头") #r("tih-la-hau-ts", "跌拉化之") #r("lau", "咾") #r("chi-le", "起来") #r("meh,", "末") #r("tsien", "箭") #r("thih-tsung", "贴準") #r("(3)", " ") #r("dzauh", "射")#footnote[Shoot up.] #r("zaung-le.", "上来。") #r("Zak-zen", "若然") #r("lau-hoo", "老虎") #r("peh", "拨") #r("tsien-dzauh-ts", "箭射之") #r("meh,", "末") #r("zieu", "就") #r("iau", "要") #r("si-theh-kuh,", "死脱个") #r("iung-we", "因为") #r("tsien", "箭") #r("deu", "头") #r("laung", "上") #r("yeu", "有") #r("dok-yah", "毒药") #r("kuh.", "个。") 

#r("La", "拉") #r("di-de-kuh", "地潭个") #r("pien-deu,", "边头") #r("zu", "柱") #r("laung", "上") #r("kwo", "挂") #r("(4)", " ") #r("ih-kwhe", "一块") #r("ba-ts,", "牌子。")#footnote[A sign board] #r("la", "拉") #r("ba-ts", "牌子") #r("laung", "上") #r("sia", "写") #r("liang-kyui", "两句") #r("seh-wo,", "说话") #r("wo-lau,", "话咾") #r("\"Zien-mien", "“前面") #r("yeu", "有") #r("we-hyien,", "危险") #r("tseu-loo", "走路") #r("nyung", "人") #r("'veh", "勿") #r("iau", "要") #r("zaung-chi\".", "上去”。") 

#r("'Eu-le", "后来") #r("ih-kuh", "一个") #r("nyung", "人") #r("tseu", "走") #r("tau", "到") #r("i-deu,", "伊头") #r("khoen-kyien-ts", "看见之") #r("ba-ts", "牌子") #r("zieu", "就") #r("we-tsen", "回转") #r("chi,", "去") #r("iung-we", "因为") #r("yi", "伊") #r("suh-z-kuh,", "识字个") #r("lau", "咾") #r("hyau-tuh", "晓得") #r("ba-ts", "牌子") #r("laung", "上") #r("kuh", "个") #r("seh-wo.", "说话。") 
#r("La", "拉") #r("ya", "夜") #r("li-hyang", "里向") #r("zu-laung", "柱上") #r("'veh-kwo", "勿挂") #r("ba-ts,", "牌子") #r("z", "是") #r("kwo", "挂") #r("(5)", " ") #r("ih-tsan", "一盏") #r("tung-loong,", "灯笼。")#footnote[A lantern.] #r("tung-loong", "灯笼") #r("laung", "上") #r("meh,", "末") #r("'a", "也") #r("yeu", "有") #r("z,", "字") #r("tah-ts", "搭之") #r("ba-ts", "牌子") #r("laung,", "上") #r("z", "是") #r("ih-yang-kuh.", "一样个。") 

#r("La", "拉") #r("ya-deu", "夜头") #r("yeu", "有") #r("ih-kuh", "一个") #r("hyang-'au-nyung", "乡下人") #r("tseu-tau", "走到") #r("i-deu,", "伊头") #r("khoen-kyien-ts", "看见之") #r("tung-loong,", "灯笼。") #r("yi", "伊") #r("siang", "想") #r("san-laung", "山上") #r("sing", "新") #r("khe", "开") #r("(1)", " ") #r("wung-daung", "混堂")#footnote[A bath house.] #r("lau,", "咾") #r("iau-siang", "要想") #r("zaung-chi", "上去") #r("zing", "净") #r("ih-kuh", "一个") #r("yok,", "浴") #r("iung-we", "因为") #r("yi", "伊") #r("'veh", "勿") #r("suh-z-kuh", "识字个") #r("lau", "咾") #r("siang", "想") #r("tau", "到") #r("wung-daung-kuh", "混堂个") #r("z-thi,", "事体") #r("we-ts", "为之") #r("wung-daung", "混堂") #r("mung-kheu-deu", "门口头") #r("z", "是") #r("yeu", "有") #r("ih-tsan", "一盏") #r("tung-loong-kuh.", "灯笼个。") 

#r("Di-kuh", "第个") #r("hyang-'au-nyung", "乡下人") #r("zieu", "就") #r("bau-zaung", "跑上") #r("chi", "去") #r("lau", "咾") #r("(2)", " ") #r("dah", "踏") #r("la", "拉") #r("di-de", "地潭")#footnote[Stepped into the pit.] #r("li-kuh", "里个") #r("tsien", "箭") #r("laung", "上") #r("lau", "咾") #r("peh-la", "拨拉") #r("tsien", "箭") #r("zauh-sah-tse.", "射杀者。") #r("Di-kuh", "第个") #r("z", "是") #r("'veh", "勿") #r("suh-z", "识字") #r("kuh", "个") #r("'e-tshu", "害处") #r("yan.", "也。")
