#import "../../template.typ": exercise, r

#exercise(47, "论天气使人成功毛病", "LUNG THIEN-CHI-S NYUNG DZUNG-KOONG MAU-BING")

#r("Zien", "前") #r("li-pa-lok,", "礼拜六") #r("thien-chi", "天气") #r("zeh-dze", "实在") #r("thuh", "忒") #r("foong-liang,", "风凉，")#footnote[Cool.] #r("doo", "大") #r("'veh-siang-phe", "勿相配")#footnote[Unfitting.] #r("'au-li-kuh", "夏里个") #r("thien-chi,", "天气，") 
#r("khoong-pho", "恐怕") #r("yeu", "有") #r("too-hau-nyung", "多化人") #r("we-ts", "为之") #r("'veh-lieu-sing", "勿留心")#footnote[Not careful.] #r("tsak-i-zaung,", "着衣裳，") #r("dzak-ts-lang", "着之冷")#footnote[Take cold.] #r("lau", "咾") #r("sang-bing.", "生病。") 
#r("Nyung", "人") #r("dzak-ts-lang", "着之冷") #r("meh,", "末") #r("tsoong", "终") #r("yeu", "有") #r("kheh-seu-kuh", "咳嗽个")#footnote[Cough.] #r("mau-bing.", "毛病。") 
#r("Zak-zen", "若然") #r("thoo-dzang-ts", "拖长之")#footnote[Prolong.] #r("nyih-kyak", "日脚") #r("meh,", "末，") #r("khoong-pho", "恐怕") #r("iau", "要") #r("dzung-koong", "成功") #r("lau-bing,", "痨病，") #r("zieu", "就是") #r("z", "肺里个") #r("fi-li-kuh", "毛病。")#footnote[Lungs.] #r("mau-bing,", "所以是") 
#r("soo-i", "烦难") #r("z", "医好个。") #r("van-nan", "拉") #r("i-hau-kuh.", "几年") 
#r("La", "前头个") #r("kyi-nyien", "医生") #r("zien-deu-kuh", "想勿出") #r("i-sang,", "医好") #r("siang-'veh-tsheh", "第个") #r("i-hau", "病个") #r("di-kuh", "法则。") #r("bing", "前日子") #r("kuh", "我拉") #r("fah-tsuh.", "看") 

#r("Zien-nyih-ts", "新闻纸") #r("ngoo", "看到") #r("la", "纽约省个") #r("khoen", "总督") #r("sing-vaung-ts,", "伊") #r("khoen", "讲论") #r("tau", "第个") #r("Neu-yak-sang-kuh", "毛病")#footnote[New York.] #r("tsoong-tok,", "实在")#footnote[Governor.] #r("yi", "是") #r("kaung-lung", "要") #r("di-kuh", "过人个。") #r("mau-bing,", "所以") 
#r("zeh-dze", "议定当") #r("z", "规矩，") #r("iau", "凡系") #r("koo-nyung-kuh,", "医生") #r("soo-i", "看着") #r("nyi-ding-taung", "第个") #r("kwe-kyui;", "毛病") #r("van-i", "末") #r("i-sung", "一定") #r("khoen-dzak", "要") #r("di-kuh", "报明") #r("mau-bing", "官府") #r("meh,", "咾") #r("ih-ding", "拿") #r("iau", "第个") #r("pau-ming", "病人")#footnote[Report.] #r("kwen-foo", "搭好拉个人") #r("lau,", "分开来") #r("nau", "住，") #r("di-kuh", "免之") #r("bing-nyung", "第个") #r("tah", "毛病") #r("hau", "传开") #r("la-kuh-nyung", "拉") #r("fung-khe", "国度里") #r("le", "咾") #r("dzu,", "多起来。") #r("mien-ts", "我")#footnote[Avoid.] #r("di-kuh", "听见") #r("mau-bing", "有人") #r("dzen-khe", "话，")#footnote[Spread.] #r("la", "有个") #r("kok-doo", "毛病个") #r("li", "人") #r("lau", "顶好") #r("too-chi-le.", "末") 
#r("Ngoo", "是") #r("thing-khien", "睏拉") #r("yeu", "帐篷") #r("nyung", "里") #r("wo,", "或者") #r("yeu", "拉") #r("di-kuh", "高山上") #r("mau-bing-kuh", "咾") #r("nyung,", "松树林") #r("ting-hau", "当中。") #r("meh,", "因为") #r("z", "第个") #r("kwhung-la", "地方个") #r("tsang-boong", "气")#footnote[Tent.] #r("li,", "是") #r("'ok-tse", "清洁") #r("la", "咾") #r("kau-san", "拨") #r("laung", "病人") #r("lau", "有") #r("soong-zu", "益个。") 
#r("ling", "拉") #r("taung-tsoong,", "美国个")#footnote[Among the pines.] #r("iung-we", "南面，") #r("di-kuh", "有") #r("di-faung-kuh", "一处") #r("chi,", "地方，") #r("z", "是") #r("tshing-kyih", "已经") #r("lau,", "为之") #r("peh", "痨病") #r("bing-nyung", "人") #r("yeu", "咾") #r("iuh-tshu.", "特为") 

#r("La", "设立") #r("Me-kok-kuh", "美国个") #r("nen-mien,", "南面，") #r("yeu", "有") #r("ih-tshu", "一处") #r("di-faung,", "地方，") #r("z", "是") #r("i-kyung", "已经") #r("we-ts", "为之") #r("lau-bing", "痨病") #r("nyung", "人") #r("lau,", "咾") #r("duh-we", "特为") #r("seh-lih", "设立") #r("ih-kuh", "一个") #r("hau", "好") #r("di-faung", "地方") #r("peh", "拨") #r("yi-la", "伊拉") #r("tung.", "登。") #r("Di-kuh", "第个") #r("di-faung,", "地方，") #r("z", "是") #r("la", "拉") #r("nen-faung,", "南方，") #r("thien-chi", "天气") #r("ih-nyien", "一年") #r("tau-deu", "到头") #r("z", "是") #r("wung-oo", "温和") #r("kuh,", "个。") #r("toong-thien", "冬天") #r("tah-ts", "搭之") #r("ji-thien,", "夏天，") #r("'oen-su", "寒暑") #r("piau", "表") #r("laung", "上") #r("pih-koo", "不过") #r("zaung-lauh", "上落") #r("ng-doo.", "五度。") #r("I-deu-kuh", "伊头个") #r("bing-nyung,", "病人，") #r("yeu-kuh", "有个") #r("kwhung-la", "睏拉") #r("loo-thien,", "露天，") #r("yeu-kuh", "有个") #r("kwhung-la", "睏拉") #r("tsang-boong", "帐篷") #r("li.", "里。") #r("I-kyung", "已经") #r("yeu", "有") #r("kyi-tshien-nyung", "几千人") #r("tung-la", "登拉") #r("i-kwhe.", "伊块。") #r("Yeu-kuh-meh", "有个") #r("tung-ts", "登之") #r("kyi-kuh-nyoeh", "几个月") #r("lau", "咾") #r("hau", "好") #r("kuh,", "个，") #r("yeu-kuh", "有个") #r("tung-ts", "登之") #r("nyien-po", "年把") #r("lau", "咾") #r("hau-kuh.", "好个。") 
#r("Di-kuh", "第个") #r("i-bing", "医病个") #r("fah-tsuh,", "法则") #r("zeh-dze", "实在是") #r("z", "再好") #r("tse-hau", "无没") #r("m-meh-kuh", "个") #r("tse.", "者。")
