#import "../../template.typ": r, exercise

#exercise(59, "论到苏州咾杭州", "LUNG TAU SOO-TSEU LAU 'AUNG-TSEU")

#r("Zok", "俗语") #r("nyui", "话") #r("wo,", "“上") #r("(2) Zaung", "有")#footnote[Above is heaven, blow are Soochow and Hangchow.] #r("yeu", "天堂，") #r("Thien-daung,", "下") #r("'au", "有") #r("yeu", "苏") #r("Soo,", "杭”，") #r("'Aung\"", "所以") #r("soo-i", "苏州") #r("Soo-tseu", "咾") #r("lau", "杭州") #r("'Aung-tseu", "算") #r("soen", "中国") #r("Tsoong-kok", "顶好") #r("ting", "个") #r("hau", "地方。") #r("kuh", "到") #r("di-faung,", "之") #r("tau-ts", "春天") #r("tshung-thien,", "景致") #r("kyung-ts", "更加") #r("kung-ka", "好看。") #r("hau", "桃花") #r("khoen,", "末") 
#r("(3) dau-hwo", "红，")#footnote[Peach blossoms.] #r("meh", "杨柳") #r("'oong,", "末") #r("(4) yang-lieu", "绿，")#footnote[The willow tree.] #r("meh", "天气") #r("lok,", "和暖") #r("thien-chi", "个") #r("'oo-noen-kuh", "时候") #r("z-'eu,", "到") #r("tau", "苏州") #r("Soo-tseu", "咾") #r("lau", "杭州") #r("'Aung-tseu", "去") #r("chi", "勃相") #r("beh-siang-siang,", "勃相，") #r("z", "是") #r("man", "蛮") #r("yeu", "有趣") #r("tshui", "个") #r("kuh,", "而且") #r("r-tshia", "卫生") #r("we", "也有") #r("sung", "益处") #r("'a", "个。") #r("yeu", "现在") #r("iuh-tshu", "有") #r("kuh.", "火轮车") 
#r("Yien-dze", "去") #r("yeu", "咾") #r("hoo-lung", "来，") #r("tsho", "蛮") #r("chi", "便当；") #r("lau", "有") #r("le,", "多化") #r("man", "相信") #r("bien-taung;", "菩萨") #r("yeu", "个") #r("too-hau", "人") #r("siang-sing", "全") #r("boo-sah", "欢喜") #r("kuh", "到") #r("nyung,", "杭州") #r("zen", "去，") #r("hwen-hyi", "是") #r("tau", "闹猛") #r("'Aung-tseu", "来死。") #r("chi,", "但是") #r("z", "我") #r("nau-mang-le-si.", "想") 
#r("Dan-z", "烧香") #r("ngoo", "咾啥，") #r("siang", "不过") #r("sau-hyang", "费脱") #r("lau-sa,", "有用") #r("pih-koo", "个") #r("(5) fi-theh", "铜钱")#footnote[Expend.] #r("yeu-yoong-kuh", "咾") #r("doong-dien", "做") #r("lau,", "无用") #r("tsoo", "个") #r("m-yoong-kuh", "事体。") #r("z-thi.", "旧年") 
#r("Jeu", "我") #r("nyien", "听得") #r("ngoo", "有") #r("thing", "一只") #r("tuh", "烧香船，") #r("yeu", "为之") #r("ih-tsak", "人") #r("sau-hyang", "劫来") #r("zen,", "忒") #r("we-ts", "多") #r("nyung", "以致") #r("gah-le", "打翻") #r("thuh-too,", "拉") #r("i-ts", "河里") #r("(6) tang-fan", "沉杀")#footnote[Overturn.] #r("la", "之") #r("'oo-li,", "多个") #r("dzung-sah-ts", "人。") #r("ta-kuh", "伊拉") #r("nyung.", "要求") #r("Yi-la", "福气") #r("iau", "倒") #r("jeu", "得着") #r("fok-chi,", "祸患，") #r("tau", "所以") #r("tuh-dzak", "现在") #r("(7) oo-wan,", "有个")#footnote[Calamity.] #r("soo-i", "明白") #r("yien-dze", "个") #r("yeu", "人") #r("kuh", "拿") #r("ming-bak-kuh", "第个") #r("nyung,", "烧香") #r("nau", "个") #r("di-kuh", "铜钱") #r("sau-hyang-kuh", "助赈济") #r("doong-dien", "咾") #r("(8) zoo", "做好") #r("tsung-tsi", "事") #r("lau,", "哉。") #r("tsoo", "comb") #r("hau-z", "the") #r("tse.", "hair") 
