#import "../../template.typ": r, exercise

#exercise(56, "论四马路", "LUNG S-MO-LOO")

#r("Leh-la", "拉拉") #r("Zaung-he", "上海") #r("beh-siang", "勃相") #r("kuh", "个") #r("di-faung", "地方") #r("taung-tsoong.", "当中。") 
#r("S-mo-loo", "四马路") #r("(1) ming-sang", "名声")#footnote[Reputation.] #r("z", "是") #r("ting-doo.", "顶大。") 
#r("Di-diau", "第条") #r("loo", "路") #r("kuh", "个") #r("yang-suh", "样式") #r("hau-ziang", "好像") #r("(2) Eu-loo-po", "欧罗巴")#footnote[Europe.] #r("dzung", "城") #r("li", "里") #r("kuh", "个") #r("loo,", "路，") #r("dan-z", "但是") #r("loong-tsoong", "拢总") #r("kuh", "个") #r("(3) yien-ka", "沿街")#footnote[Houses bordering on street.] #r("vaung-ts", "房子") #r("tsau", "照") #r("Tsoong-kok", "中国") #r("kuh", "个") #r("yang-suh", "样式") #r("lau", "咾") #r("zau", "造") #r("la", "拉") #r("kuh.", "个。") 
#r("Leh-la", "拉") #r("di-diau", "第条") #r("loo", "路") #r("laung", "上") #r("yeu", "有") #r("too-hau", "多化") #r("dzo-kwen", "茶馆") #r("lau", "咾") #r("van-tien,", "饭店，") #r("'a", "也有") #r("yeu", "五") #r("ng", "六片") #r("lok", "影戏场") #r("ban", "拉拉") #r("(4) iung-hyi", "近边")#footnote[Stereopticon show place.] #r("dzang.", "个") 

#r("Leh-la", "地方") #r("jung", "也有") #r("pien-kuh", "四") #r("di-faung,", "五片") #r("'a", "戏馆。") #r("yeu", "另外") #r("s", "还有") #r("ng", "许多") #r("ban", "算命") #r("hyi-kwen,", "先生") #r("ling-nga", "咾") #r("wan-yeu", "讲") #r("hyui-too", "故事") #r("(5) soen-ming", "个")#footnote[Fortune teller.] #r("sien-sang", "人") #r("lau", "变戏法") #r("kaung", "个") #r("koo-z-kuh", "人") #r("nyung,", "咾") 
#r("(6) pien-hyi-fah-kuh", "小")#footnote[A juggler.] #r("nyung", "零碎个") #r("lau", "勃相") #r("siau", "物事。") #r("ling-se-kuh", "因为") #r("beh-siang", "第条") #r("meh-z,", "路") #r("iung-we", "是") #r("di-diau", "蛮") #r("loo", "好") #r("z", "勃相") #r("man-hau", "个") #r("beh-siang-kuh", "场化。") #r("dzang-hau.", "每日") 

#r("Me", "夜里") #r("nyih", "有") #r("ya-li", "交关") #r("yeu", "人") #r("kyau-kwan", "到") #r("nyung", "伊头") #r("tau", "去") #r("i-deu", "勃相") #r("chi", "咾") #r("beh-siang", "散散心。") #r("lau", "四马路") #r("(7) san-san", "勿但是")#footnote[To take recreation.] #r("sing.", "蛮好") 
#r("S-mo-loo", "勃相") #r("'veh", "个") #r("dan-z", "地方，") #r("man-hau", "拉拉") #r("beh-siang-kuh", "东面") #r("di-faung,", "还有") #r("leh-la", "多化") #r("toong", "洋行") #r("mien", "咾") #r("wan", "大个") #r("yeu", "行家，") #r("too-hau", "也有") #r("yang-'aung", "老") #r("lau", "巡捕房，") #r("doo-kuh", "就是") #r("'aung-ka,", "上海") #r("'a", "顶大") #r("yeu", "个") #r("Lau-dzing-boo", "巡捕房。") #r("vaung,", "也有") #r("zieu-z", "药房") #r("Zaung-he", "咾") #r("ting", "牙医生。") #r("doo-kuh", "也有") #r("Dzing-boo", "广东") #r("vaung,", "宵夜馆") #r("'a", "咾") #r("yeu", "炒麵店。") 
#r("(8) yak-vaung", "拢总")#footnote[Druggist chemist.] #r("lau", "个") #r("(9) nga-i-sung,", "店")#footnote[Dentist.] #r("'a", "咾") #r("yeu", "消閒") #r("Kwaung-toong", "个") #r("(10) siau", "地方")#footnote[A pleasure house.] #r("ya", "是") #r("kwen,", "中国") #r("lau", "各处") #r("(1) tshau-mien-tien.", "地方")#footnote[A Chinese restaurant.] 
#r("Loong-tsoong", "个") #r("kuh", "人") #r("tien", "开拉个。") #r("lau", "若然") #r("(2) siau-an", "人")#footnote[A pleasure place.] #r("kuh", "走过") #r("di-faung", "第条") #r("z", "路") #r("Tsoong-kok", "可以") #r("kauh-tshu", "听见") #r("di-faung", "十八省") #r("kuh", "个") #r("nyung", "人") #r("khe", "大家") #r("la", "白话。") #r("kuh.", "我") 
#r("Zak-zen", "必过") #r("nyung", "大畧") #r("tseu", "讲") #r("koo", "拨哪") #r("di-diau", "听。") #r("loo,", "若然") #r("khau-i", "哪") #r("thing-kyien", "要") #r("zeh-pah-sang-kuh", "仔细") #r("nyung", "晓得") #r("da-ka", "末，") #r("bak-wo.", "应该") 

#r("Ngoo", "自家") #r("pih-koo", "去") #r("da-liak", "看看") #r("kaung", "咾") #r("peh", "一定") #r("na", "可以") #r("thing.", "看见") #r("Zak-zen", "许多") #r("na", "稀奇") #r("iau", "古怪") #r("ts-si", "个") #r("hyau-tuh", "物事") #r("meh,", "咾") #r("iung-ke", "别样") #r("z-ka", "有") #r("chi", "滋味") #r("khoen-khoen", "个") #r("lau", "事体。") #r("ih", "一定") #r("ding", "可以") #r("khau-i", "看见") #r("khoen-kyien", "许多") #r("hyui-too", "稀奇") #r("(3) hyi-kyi", "古怪")#footnote[Strange.] #r("koo-kwa", "个") #r("kuh", "物事") #r("meh-z", "咾") #r("lau", "别样") #r("bih-yang", "有") #r("yeu", "滋味") #r("(4) ts-mi", "个")#footnote[Flavor.] #r("kuh", "事体。") #r("z-thi.", "comb") 
