#import "../../template.typ": r, exercise

#exercise(55, "论招开车子个人", "LUNG TSAU KHE TSHO-TS-KUH NYUNG")

#r("Zien-kuh", "前个") #r("nyoeh", "月") #r("dien-chi", "电气") #r("koong-s-kuh", "公司个")#footnote[Electric company.] #r("da-pan", "大班") #r("tsha", "差") #r("ih", "一个") #r("kuh", "副") #r("foo", "买办") #r("ma-ban", "搭之")#footnote[Assistant.] #r("tah-ts", "账房") #r("tsang-vaung,", "到")#footnote[Shroff compradore.] #r("tau", "镇江") #r("Tsung-kaung", "去，")#footnote[Chinkiang.] #r("chi,", "招") #r("tsau", "伊头个") #r("i-deu-kuh", "人") #r("nyung", "到") #r("tau", "上海") #r("Zaung-he", "来") #r("le", "学") #r("'auh", "开车子。") #r("khe", "现在") #r("tsho-ts.", "听得")#footnote[To run the trams.] 
#r("Yien-dze", "话") #r("thing-tuh", "第个") #r("wo,", "多化") #r("di-kuh", "人") #r("too-hau", "到") #r("nyung,", "上海") #r("tau", "来") #r("Zaung-he", "大约") #r("le", "有") #r("da-iak", "念三个") #r("yeu", "人。") #r("nyan-san", "但是") #r("kuh", "全") #r("nyung,", "是") #r("dan-z", "乡下") #r("zen", "人。") #r("z", "有个") #r("hyang-'au", "从前") #r("nyung,", "是") #r("yeu", "扫") #r("kuh", "垃圾") #r("dzoong-zien", "个，") #r("z", "有个") #r("sau", "末") #r("la-si", "当") #r("kuh,", "警察局") #r("yeu", "巡捕") #r("kuh", "个。") #r("meh", "因为") #r("taung", "伊头个") #r("kyung-tshah-jok", "工钱") #r("dzing-boo", "是") #r("kuh.", "少个。")#footnote[Chinese guard police.] 
#r("Iung-we", "每") #r("i-deu", "人") #r("kuh", "只") #r("koong-dien", "得") #r("z", "五千") #r("sau-kuh,", "铜钱") #r("me", "一") #r("nyung", "个") #r("tsuh", "月。") #r("tuh", "所以") #r("ng", "一") #r("tshien", "听得") #r("doong-dien", "上海") #r("ih-kuh", "拨") #r("nyoeh,", "伊") #r("soo-i", "八块") #r("ih", "洋钱") #r("thing-tuh", "一") #r("Zaung-he", "个") #r("peh", "月，") #r("yi", "也") #r("pah-kwhe", "拨") #r("yang-dien", "房子") #r("ih-kuh", "住，") #r("nyoeh,", "也") #r("'a", "拨") #r("peh", "饭") #r("yi", "拉") #r("vaung-ts", "伊") #r("dzu,", "吃，") #r("'a", "也") #r("peh", "拨") #r("van", "衣裳") #r("la", "拉") #r("yi", "伊") #r("chuh,", "着。") #r("'a", "盖咾") #r("peh", "大家") #r("i-zaung", "蛮") #r("la", "高兴") #r("yi", "来。") #r("tsak,", "现在") #r("keh-lau", "听得") #r("da-ka", "话，") #r("man", "每") #r("kau-hyung", "月") #r("le.", "要") 
#r("Yien-dze", "存") #r("thing-tuh", "四块") #r("wo,", "洋钱") #r("me", "拉") #r("nyoeh", "银行") #r("iau", "里。") #r("dzung", "若然") #r("s-kwhe", "后首") #r("yang-dien", "逃走") #r("la", "或者") #r("nyung-'aung", "有") #r("li,", "啥") #r("zak-zen", "差错") #r("'eu-seu", "末") #r("dau-tseu,", "第个") #r("'ok-tse", "存") #r("yeu", "款项") #r("sa", "要") #r("tsho-tshu", "充公") #r("meh,", "个。") #r("di-kuh", "现在") #r("dzung-aung", "也")#footnote[A bank deposit.] #r("iau", "听得") #r("tshoong-koong", "话") #r("kuh.", "先") 
#r("Yien-dze", "要") #r("'a", "学") #r("thing-tuh", "一个") #r("wo,", "月。") #r("sien", "若然") #r("iau", "学得") #r("'auh", "来") #r("ih-kuh", "难末") #r("nyoeh,", "算") #r("zak-zen", "工钱。") #r("'auh", "但是") #r("tuh-le,", "现在") #r("nan-meh", "来个") #r("soen", "念三个") #r("koong-dien,", "人") #r("dan-z", "内中") #r("yien-dze", "有") #r("le", "一半") #r("kuh", "已经") #r("nyan-san", "逃走") #r("kuh", "咾") #r("nyung", "勿") #r("nen-tsoong", "情愿") #r("yeu", "做") #r("ih-pen", "第个") #r("i-kyung", "生活。") #r("dau-tseu", "况且") #r("lau", "老底子个") #r("'veh", "多化") #r("dzing-nyoen", "开车子个") #r("tsoo", "人") #r("di-kuh", "常庄") #r("sang-weh,", "请假。") #r("hwaung-tshien", "所以") #r("lau-ti-ts-kuh", "近来")#footnote[The old motor men.] #r("too-hau-ke-tsho-ts", "有") #r("kuh", "多化") #r("nyung", "买") #r("dzang-tsaung", "票子个") #r("tshing", "人") #r("ka.", "拉拉")#footnote[Ask for leave.] 
#r("Soo-i", "做") #r("jung-le", "第个") #r("yeu", "生活。") #r("too-hau", "又") #r("ma", "听得") #r("phiau-ts-kuh", "话") #r("nyung", "因为") #r("leh-la", "公司里") #r("tsoo", "忒") #r("di-kuh", "凶，") #r("sang-weh.", "每") #r("Yi", "月") #r("thing-tuh", "工钱") #r("wo,", "勿大") #r("iung-we", "有，") #r("koong-s-li", "一颜") #r("thuh-hyoong,", "做")#footnote[Too severe.] #r("me", "差") #r("nyoeh", "末") #r("koong-dien", "就") #r("'veh", "要") #r("doo,", "罚") #r("yeu", "个。") #r("ih", "况且") #r("ngan", "做") #r("tsoo", "生活个") #r("tsho", "辰光") #r("meh,", "也") #r("zieu", "忒") #r("iau", "长远。") #r("vah", "所以") #r("kuh,", "有") #r("hwaung-tshien", "交关") #r("tsoo", "人") #r("sang-weh", "勿") #r("kuh", "高兴") #r("zung-kwaung,", "做") #r("'a", "第个") #r("thuh", "生意") #r("dzang", "哉。") #r("yoen.", "照") 
#r("Soo-i", "我") #r("yeu", "想起来") #r("kyau-kwan", "电气") #r("nyung", "公司") #r("'veh", "应该") #r("kau-hyung", "好好能") #r("tsoo", "待") #r("di", "开") #r("kuh", "车子个") #r("sang-i", "人。") #r("tse.", "既然") 
#r("Tsau", "有") #r("ngoo", "罚") #r("siang-chi-le,", "末") #r("dien-tsho", "应该") #r("koong-s", "有") #r("iung-ke", "赏，")#footnote[Tram company.] #r("hau-hau", "实在") #r("nung", "做") #r("de", "末") #r("khe", "人") #r("tsho-ts", "肯") #r("kuh", "到") #r("nyung,", "公司") #r("kyi-zen", "里") #r("yeu", "来") #r("vah", "做") #r("meh,", "事体") #r("iung-ke", "哉。") #r("yeu", "否则") #r("saung,", "末")#footnote[Present, reward.] #r("zeh-ke", "人") #r("tsoo", "终") #r("meh,", "勿") #r("nyung", "肯") #r("khung", "来") #r("tau", "个。") #r("koong-s", "公司") #r("li", "里") #r("le", "来") #r("tsoo", "做") #r("z-thi", "事体") #r("tse.", "哉。") #r("'Veh-zen", "否则") #r("meh,", "末") #r("nyung", "人") #r("tsoong", "终") #r("'veh", "勿") #r("khung", "肯") #r("le", "来") #r("kuh.", "个。")
